-- 1. 모든 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
;
-- 2. 부서가 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NULL
;
-- 3. 직무가 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE JOB_ID IS NULL
;
-- 4. 부서와 직무가 모두 있는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE JOB_ID IS NOT NULL
   AND DEPARTMENT_ID IS NOT NULL
;
-- 5. 부서장이 없는 모든 부서의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
	 , DEPARTMENT_NAME 
	 , LOCATION_ID 
	 , MANAGER_ID 
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NULL
;
-- 6. 부서장이 있는 모든 부서의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
	 , DEPARTMENT_NAME 
	 , LOCATION_ID 
	 , MANAGER_ID 
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NOT NULL
;
-- 7. 부서장의 모든 사원 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
 						 FROM DEPARTMENTS
 						WHERE MANAGER_ID IS NOT NULL)
;
-- 8. 사원의 이름만 조회한다.
SELECT FIRST_NAME
  FROM EMPLOYEES
;
-- 9. 사원의 이름이 7자리인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM (SELECT EMPLOYEE_ID
			 , FIRST_NAME
			 , LAST_NAME
			 , EMAIL
			 , PHONE_NUMBER
			 , HIRE_DATE
			 , JOB_ID
			 , SALARY
			 , COMMISSION_PCT
			 , MANAGER_ID
			 , DEPARTMENT_ID
			 , LENGTH(FIRST_NAME) AS NAME_LEN
		  FROM EMPLOYEES)
 WHERE NAME_LEN = 7
;
-- 10. 사원의 이메일이 6자리인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM (SELECT EMPLOYEE_ID
			 , FIRST_NAME
			 , LAST_NAME
			 , EMAIL
			 , PHONE_NUMBER
			 , HIRE_DATE
			 , JOB_ID
			 , SALARY
			 , COMMISSION_PCT
			 , MANAGER_ID
			 , DEPARTMENT_ID
			 , LENGTH(EMAIL) AS MAIL_LEN
		  FROM EMPLOYEES)
 WHERE MAIL_LEN = 6
;
-- 11. 모든 지역의 모든 정보를 조회한다.
SELECT LOCATION_ID
	 , CITY 
	 , COUNTRY_ID 
	 , POSTAL_CODE 
	 , STATE_PROVINCE 
	 , STREET_ADDRESS 
  FROM LOCATIONS 
;
-- 12. 지역이 없는 모든 부서의 정보를 조회한다.
SELECT D.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME 
	 , D.MANAGER_ID 
  FROM DEPARTMENTS D
 WHERE D.LOCATION_ID IS NULL
;
-- 13. 지역이 있는 모든 부서의 정보와 도시 정보를 조회한다.
SELECT D.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME 
	 , D.LOCATION_ID 
	 , D.MANAGER_ID 
	 , L.CITY 
  FROM DEPARTMENTS D
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
;
-- 14. 모든 사원의 모든 정보와 부서명을 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 15. 111번 사원의 모든 정보와 부서명을 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.EMPLOYEE_ID = 111
;
-- 16. 115번의 사원의 모든 정보와 부서명, 직무명을 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOBS J
  	ON E.JOB_ID = J.JOB_ID 
  LEFT OUTER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.EMPLOYEE_ID = 115
;
-- 17. 100번 사원의 모든 정보와 부서명, 직무명, 도시명을 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE E.EMPLOYEE_ID = 100
;
-- 18. 부서아이디별 사원의 평균급여를 조회한다.
SELECT D.DEPARTMENT_ID
	 , AVG(E.SALARY) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_ID 
 ORDER BY D.DEPARTMENT_ID ASC
;
-- 19. 직무아이디별 사원의 최고급여를 조회한다.
SELECT J.JOB_ID 
	 , MAX(E.SALARY) AS MAX_SAL 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_ID
 ORDER BY MAX_SAL ASC
;
-- 20. 부서명별 사원의 수를 조회한다.
SELECT D.DEPARTMENT_NAME
	 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME
 ORDER BY EMP_CNT ASC
;
-- 21. 직무명별 사원의 평균급여를 조회한다.
SELECT J.JOB_TITLE
	 , AVG(SALARY) AS SAL_AVG
  FROM EMPLOYEES E 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE 
 ORDER BY SAL_AVG ASC
;
-- 22. 부서명, 직무명별 사원의 수와 평균급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
	 , AVG(SALARY) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME
 	 , J.JOB_TITLE
 ORDER BY SAL_AVG ASC
;
-- 23. 커미션을 안받는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID 
  FROM EMPLOYEES E
 WHERE COMMISSION_PCT IS NULL
;
-- 24. 커미션을 받는 사원의 부서아이디를 중복없이 조회한다.
SELECT DISTINCT E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE COMMISSION_PCT IS NOT NULL
;
-- 25. 커미션을 받는 사원의 직무아이디를 중복없이 조회한다.
SELECT DISTINCT JOB_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL
;
-- 26. 사원이 있는 부서의 지역아이디를 조회한다.
SELECT DISTINCT D.LOCATION_ID  
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
-- 27. 사원이 없는 부서의 부서명을 조회한다.
SELECT DEPARTMENT_NAME
	 , EMP_CNT
  FROM (SELECT D.DEPARTMENT_NAME 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 RIGHT OUTER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		 GROUP BY D.DEPARTMENT_NAME )
 WHERE EMP_CNT = 0
;
-- 28. 도시별 부서의 수를 조회한다. (부서가 없으면 부서의 수는 0으로 조회한다.)
SELECT L.CITY 
	 , COUNT(D.DEPARTMENT_ID ) AS DEPT_CNT
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
  	ON L.LOCATION_ID = D.LOCATION_ID
 GROUP BY L.CITY 
 ORDER BY DEPT_CNT DESC 
;
-- 29. 도시별 사원의 평균급여를 조회한다. (사원이 없으면 평균급여는 0으로 조회한다.)
SELECT L.CITY 
	 , NVL(AVG(E.SALARY), 0) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 RIGHT OUTER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY L.CITY 
 ORDER BY SAL_AVG DESC
;
-- 30. Seattle의 부서 아이디를 조회한다.
SELECT L.CITY 
	 , D.DEPARTMENT_ID  
  FROM LOCATIONS L
 INNER JOIN DEPARTMENTS D
 	ON L.LOCATION_ID = D.LOCATION_ID 
 WHERE L.CITY = 'Seattle'
;
-- 31. Seattle에서 근무중인 사원의 모든 직무명을 중복없이 조회한다.
SELECT DISTINCT J.JOB_TITLE
  FROM LOCATIONS L
 INNER JOIN DEPARTMENTS D
 	ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN EMPLOYEES E
 	ON D.DEPARTMENT_ID = E.EMPLOYEE_ID 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 WHERE L.CITY = 'Seattle'
;
-- 32. 사원이 한명도 없는 도시를 조회한다.
SELECT CITY
	 , EMP_CNT
  FROM (SELECT L.CITY 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM LOCATIONS L
		  LEFT OUTER JOIN DEPARTMENTS D
		  	ON L.LOCATION_ID = D.LOCATION_ID
		  LEFT OUTER JOIN EMPLOYEES E
		  	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
		 GROUP BY L.CITY)
 WHERE EMP_CNT = 0
;
-- 33. 사원이 한명이라도 있는 도시를 조회한다.
SELECT L.CITY 
	 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY L.CITY 
;
SELECT CITY
	 , EMP_CNT
  FROM (SELECT L.CITY 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM LOCATIONS L
		  LEFT OUTER JOIN DEPARTMENTS D
		  	ON L.LOCATION_ID = D.LOCATION_ID
		  LEFT OUTER JOIN EMPLOYEES E
		  	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
		 GROUP BY L.CITY)
 WHERE EMP_CNT != 0
;
-- 34. 모든 사원의 정보를 급여로 오름차순 정렬하여 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.SALARY
	 , E.COMMISSION_PCT
  FROM EMPLOYEES E
 ORDER BY SALARY ASC
;
-- 35. 부서명별 평균급여를 부서명으로 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , AVG(E.SALARY) AS SAL_AVG
  FROM DEPARTMENTS D
 INNER JOIN EMPLOYEES E
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY D.DEPARTMENT_NAME DESC
;
-- 36. 부서명별 최고급여를 최고급여로 오름차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , MAX(E.SALARY) AS MAX_SAL
  FROM DEPARTMENTS D
 INNER JOIN EMPLOYEES E
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY MAX_SAL DESC
;
-- 37. 부서명이 가장 긴 부서에서 근무중인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
	 , DEPARTMENT_NAME
  FROM (SELECT E.EMPLOYEE_ID
			 , E.FIRST_NAME
			 , E.LAST_NAME
			 , E.EMAIL
			 , E.PHONE_NUMBER
			 , E.HIRE_DATE
			 , E.JOB_ID
			 , E.SALARY
			 , E.COMMISSION_PCT
			 , E.MANAGER_ID
			 , D.DEPARTMENT_ID
			 , D.DEPARTMENT_NAME 
			 , LENGTH(D.DEPARTMENT_NAME) AS D_NAME_LEN
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
			ON E.DEPARTMENT_ID = D.DEPARTMENT_ID)
 WHERE D_NAME_LEN = (SELECT MAX(LENGTH(DEPARTMENT_NAME))
 					   FROM DEPARTMENTS)
; 				
-- 38. 도시 별 사원의 수를 도시로 오름차순 정렬하여 조회한다.
SELECT L.CITY
	 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
 GROUP BY L.CITY 
 ORDER BY L.CITY ASC
;
-- 39. 모든 사원의 사원번호, 이름, 성, 급여, 커미션을 포함한 급여 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , NVL(SALARY + (SALARY * COMMISSION_PCT),0) AS COMM_SAL
  FROM EMPLOYEES
 ORDER BY COMM_SAL DESC
;
-- 40. 매년 급여의 10%의 상여금을 받는다고 했을 때, 사원별로 현재까지 받은 상여금의 합과 사원번호, 급여를 조회한다.
SELECT (SALARY * 0.1) * SERVICE_YEAR AS BONUS
	 , EMPLOYEE_ID
	 , SALARY
  FROM (SELECT EMPLOYEE_ID
			 , SALARY
			 , TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) - TO_NUMBER(TO_CHAR(HIRE_DATE, 'YYYY')) AS SERVICE_YEAR
		  FROM EMPLOYEES)
;
-- 41. 직무가 변경되었던 사원들의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH 
	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
;
-- 42. 모든 사원들의 현재 직무명과 과거의 직무명을 조회한다. 만약 직무가 한번도 변경되지 않았다면, 과거의 직무명은 '없음' 으로 조회한다.
SELECT J.JOB_TITLE
	 , NVL(JH.JOB_TITLE, '없음') 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
  LEFT OUTER JOIN (SELECT J.JOB_TITLE 
 				  , JH.EMPLOYEE_ID 
			   FROM JOB_HISTORY JH
			  INNER JOIN JOBS J
				 ON JH.JOB_ID = J.JOB_ID) JH
	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
;
-- 43. 직무가 변경될 때마다 급여가 15%씩 감소한다고 했을 때, 직무가 변경된 사원들의 감소된 급여를 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , SALARY - (SALARY * 0.15)*JH.J_CHANGED_CNT AS REDUCED_SAL
  FROM EMPLOYEES E
 INNER JOIN (SELECT E.EMPLOYEE_ID 
				 , COUNT(E.EMPLOYEE_ID ) AS J_CHANGED_CNT
			  FROM EMPLOYEES E
			 INNER JOIN JOB_HISTORY JH 
				ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
			 GROUP BY E.EMPLOYEE_ID ) JH
 	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 			 
;
-- 44. 2003년에 입사한 사원은 몇 명인지 조회한다.
SELECT COUNT(EMPLOYEE_ID)
  FROM (SELECT EMPLOYEE_ID
			 , TO_CHAR(HIRE_DATE, 'YYYY') AS HIRED_YEAR
		  FROM EMPLOYEES)
 WHERE HIRED_YEAR = '2003'
;
-- 45. 2002년부터 2006년까지 입사한 사원은 몇명인지 연도별로 조회한다.
SELECT HIRED_YEAR
	 , COUNT(EMPLOYEE_ID)
  FROM (SELECT EMPLOYEE_ID
			 , TO_CHAR(HIRE_DATE, 'YYYY') AS HIRED_YEAR
		  FROM EMPLOYEES
		 WHERE HIRE_DATE > TO_DATE('20011231', 'YYYY-MM-DD')
		   AND HIRE_DATE < TO_DATE('20070101', 'YYYY-MM-DD'))
 GROUP BY HIRED_YEAR
;
-- 46. 113번 사원의 상사의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME
	 , E.EMAIL
	 , E.PHONE_NUMBER
	 , E.HIRE_DATE
	 , E.JOB_ID
	 , E.SALARY
	 , E.COMMISSION_PCT
	 , E.MANAGER_ID
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID
						FROM EMPLOYEES
					   WHERE EMPLOYEE_ID = 113)
;
-- 47. 100번 사원의 모든 부하직원을 계층조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
  FROM EMPLOYEES
 START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;
-- 48. 113번 사원의 모든 상사를 계층조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
  FROM EMPLOYEES
 START WITH EMPLOYEE_ID = 113
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
;
-- 49. IT 부서장의 모든 부하직원을 계층조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
  FROM EMPLOYEES
  START WITH EMPLOYEE_ID = (SELECT MANAGER_ID
							  FROM DEPARTMENTS
							 WHERE DEPARTMENT_NAME = 'IT')
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID							 
;
-- 50. 모든 부서의 부서장들의 부하직원을 계층조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LEVEL
  FROM EMPLOYEES
  START WITH EMPLOYEE_ID IN (SELECT MANAGER_ID
							  FROM DEPARTMENTS
							 WHERE MANAGER_ID IS NOT NULL)
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID							 
;