-- 1. 현재 시간을 조회한다.
SELECT SYSDATE 
  FROM DUAL  -- 오라클에서 시간을 불러오려면 DUAL이라는 Dummy TablE 테이블에서 시간을 가져와야함
  -- DUAL -> Dummy TablE
  ;
-- 2. 현재 시간을 "연-월-일" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
  FROM DUAL
;
-- 3. 한 시간 전 시간을 "시:분:초" 포멧으로 조회한다.
SELECT TO_CHAR(SYSDATE - 1/24, 'HH24:MI:SS')
	 , TO_CHAR(SYSDATE, 'HH:MI:SS')
  FROM DUAL
;
-- 4. EMPLOYEES 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 ;
-- 5. DEPARTMENTS 테이블의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
	 , DEPARTMENT_NAME 
	 , MANAGER_ID 
	 , LOCATION_ID 
  FROM DEPARTMENTS
  ;
-- 6. JOBS 테이블의 모든 정보를 조회한다.
SELECT JOB_ID 
	 , JOB_TITLE 
	 , MIN_SALARY 
	 , MAX_SALARY
  FROM JOBS
  ;
-- 7. LOCATIONS 테이블의 모든 정보를 조회한다.
SELECT LOCATION_ID 
	 , STREET_ADDRESS 
	 , POSTAL_CODE 
	 , CITY 
	 , STATE_PROVINCE 
	 , COUNTRY_ID 
  FROM LOCATIONS
  ;
-- 8. COUNTRIES 테이블의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
	 , COUNTRY_NAME 
	 , REGION_ID 
  FROM COUNTRIES
  ;
-- 9. REGIONS 테이블의 모든 정보를 조회한다.
SELECT REGION_ID 
	 , REGION_NAME 
  FROM REGIONS
  ;
-- 10. JOB_HISTORY 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
	 , START_DATE 
	 , END_DATE 
	 , JOB_ID 
	 , DEPARTMENT_ID 
  FROM JOB_HISTORY 
  ;
-- 11. 상사사원번호를 중복없이 조회한다.
SELECT DISTINCT MANAGER_ID
  FROM EMPLOYEES
  ;
-- 12. 90번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES 
 WHERE DEPARTMENT_ID = 90
 ;
-- 13. 90번, 100번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.DEPARTMENT_ID IN (90, 100)
 ;
-- 14. 100번 상사의 직속 부하직원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.DEPARTMENT_ID = 100
 ;
-- 15. 111번 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.EMPLOYEE_ID = 111
;
-- 16. 직무 아이디가 AD_VP 인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.JOB_ID  = 'AD_VP'
;
-- 17. 급여가 7000 이상인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.SALARY >= 7000
;
-- 18. 직무 아이디가 'PU_CLERK'인 사원 중 급여가 3000 이상인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.JOB_ID = 'PU_CLERK' AND E.SALARY >= 3000
;
-- 19. 급여가 2500, 3500, 7000 이 아니며 직업이 SA_REP 이나 ST_CLERK 인 사원들의 
--     모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.SALARY NOT IN (2500, 3500, 7000) 
   AND E.JOB_ID IN ('SA_REP', 'ST_CLERK')
;
-- 20. 커미션을 안받는 사원들의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NULL
;
-- 21. 커미션을 받는 사원들의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NOT NULL
;
-- 22. 이름의 첫 글자가 'D' 인 사원들의 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES E 
 WHERE E.FIRST_NAME LIKE 'D%'
;
-- 23. 성의 마지막 글자가 'a' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.LAST_NAME LIKE '%a'
;
-- 24. 전화번호에 '.124.'이 포함된 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.PHONE_NUMBER LIKE '%.124.%'
;
-- 25. 이름이 4글자인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.FIRST_NAME LIKE '____'
;
-- 26. 이름이나 성에 'A' 혹은 'a' 가 포함된 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
  WHERE E.FIRST_NAME LIKE '%A%'
    OR E.FIRST_NAME LIKE '%a%'
    OR E.LAST_NAME LIKE '%a%'
    OR E.LAST_NAME LIKE '%A%'
;
-- 27. 국가명이 6자리인 국가의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
	 , COUNTRY_NAME 
	 , REGION_ID
  FROM COUNTRIES c
 WHERE c.COUNTRY_NAME LIKE '______'
;
-- 28. '20230222' 문자 데이터를 날짜로 변환해 조회한다.(DUAL)
SELECT TO_DATE('20230222', 'YYYY-MM-DD')
  FROM DUAL
  ;

-- 29. '20230222' 문자 데이터를 'YYYY-MM' 으로 변환해 조회한다.(DUAL)
SELECT TO_CHAR(
	   TO_DATE('20230222', 'YYYY-MM-DD'), 'YYYY-MM-DD')
  FROM DUAL
  ;
-- 30. '20230222130140' 문자 데이터를 'YYYY-MM-DD HH24:MI:SS' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(
	   TO_DATE('20230222130140', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
  FROM DUAL
  ;
-- 31. '20230222' 날짜의 열흘 후의 날짜를 'YYYY-MM-DD' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(
	   TO_DATE('20230222', 'YYYY-MM-DD') + 10, 'YYYY-MM-DD')
  FROM DUAL
  ;
-- 32. 직원의 입사일자를 '연-월-일' 형태로 조회한다.
SELECT TO_CHAR(HIRE_DATE , 'YYYY-MM-DD')
  FROM EMPLOYEES
 ;
-- 33. 2005년 09월에 입사한 사원들의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
  WHERE HIRE_DATE >= TO_DATE('2005-09-01')
    AND HIRE_DATE <= TO_DATE('2005-10-01')-1
;
-- 34. 현재 시간으로부터 20년 전 보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT  EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
  WHERE HIRE_DATE < ADD_MONTHS(SYSDATE , -240)
;

-- 35. 사원들의 정보 중 입사연도, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	 , FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
;
-- 36. 사원들의 정보 중 입사연도, 입사월, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS HIRED_YEAR
	 , TO_CHAR(HIRE_DATE, 'MM') AS HIRED_MONTH
	 , FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
;
-- 37. MOD 함수를 통해 사원번호가 홀수면 남자, 짝수면 여자 로 구분해 조회한다. MOD(값, 나눌값)
SELECT EMPLOYEE_ID
	 , CASE WHEN SEX = 1 THEN '남'
	 		  ELSE '여'
	 		  END AS S
  FROM (SELECT EMPLOYEE_ID
	 		 , MOD(EMPLOYEE_ID, 2) AS SEX
	 	  FROM EMPLOYEES)
;
SELECT EMPLOYEE_ID
	 , CASE 
		 	WHEN
	 			MOD(EMPLOYEE_ID, 2) = 1 THEN '남'
	 		ELSE
	 			'여'
	 		END AS S
  FROM EMPLOYEES
;
SELECT EMPLOYEE_ID
	 , CASE MOD(EMPLOYEE_ID, 2)
		 	WHEN
	 			 1 THEN '남'
	 		ELSE
	 			'여'
	 		END AS S
  FROM EMPLOYEES
;
-- 38. 사원 모든 정보 중 이메일만 모두 소문자로 변경하여 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , LOWER(EMAIL) AS EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
;
-- 39. 사원의 급여를 TRUNC(소수점 버림) 함수를 사용해 100 단위는 버린채 다음과 같이 조회한다. 
--     예> 3700 -> 3000, 12700 -> 12000
SELECT TRUNC(SALARY/1000)*1000
  FROM EMPLOYEES
;
-- 40. 100단위를 버린 사원의 급여 별 사원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE SALARY = TRUNC(SALARY /1000)*1000
 GROUP BY TRUNC(SALARY /1000)*1000
;

SELECT SAL
	 , COUNT(EMPLOYEE_ID)
  FROM (SELECT EMPLOYEE_ID
  			 , TRUNC(SALARY/1000)*1000 AS SAL
  		  FROM EMPLOYEES)
  GROUP BY SAL
  ORDER BY SAL ASC
;
-- 41. 모든 사원들의 이름을 10자리로 맞추어 조회한다.
SELECT FIRST_NAME
	 , LPAD(FIRST_NAME, 10, '_')
  FROM EMPLOYEES
;
-- 42. 사원의 이름과 성을 이용해 EMAIL과 같은 값으로 만들어 조회한다.
SELECT SUBSTR(FIRST_NAME,1,1) || UPPER(SUBSTR(LAST_NAME,1,7)) AS RESULT
	 , EMAIL
  FROM EMPLOYEES
;
-- 43. 모든 사원들의 이름을 10자리로 변환해 조회한다. 예> 이름 => "        이름"
SELECT FIRST_NAME || '=> ' || '"' || LPAD(FIRST_NAME, 10, ' ') || '"'
  FROM EMPLOYEES
;
-- 44. 모든 사원들의 성을 10자리로 변환해 조회한다. 예> 성 => "성         "
SELECT LAST_NAME || '=> ' || '"' ||RPAD(LAST_NAME, 10, ' ')|| '"'
  FROM EMPLOYEES
;
-- 45. 모든 사원들의 모든 정보를 조회한다. 
--     단, 커미션을 받는 사원은 "커미션여부" 컬럼에 "Y"를, 아닌 경우 "N"으로 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
	 , CASE 
		 	WHEN COMMISSION_PCT IS NULL THEN 'N'
			ELSE 'Y'
		END AS COMM
  FROM EMPLOYEES
;
-- 46. 사원의 모든 정보를 조회한다. 
--     사원의 급여가 5000 이하이면 "사원", 
--                7000 이하이면 "대리", 
--                9000 이하이면 "과장", 
--                그 외에는 "임원" 으로 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
	 , CASE 
		 	WHEN SALARY <= 5000 THEN '사원'
	 		WHEN SALARY <= 7000 THEN '대리'
	 		WHEN SALARY <= 9000 THEN '과장'
	 		ELSE '임원'
	 		END AS POSITION
  FROM EMPLOYEES
;
-- 47. 모든 사원들의 모든 정보를 급여 오름차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY SALARY ASC
;
-- 48. 모든 사원들의 모든 정보를 이름 내림차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY FIRST_NAME DESC
;
-- 49. 모든 사원들의 모든 정보를 직무 오름차순, 급여 내림차순으로 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY JOB_ID  ASC,
 	 SALARY DESC
;
-- 50. 가장 늦게 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE)
 					  FROM EMPLOYEES
 					  )
;
-- 51. 가장 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE)
 					  FROM EMPLOYEES
 					  )
;
-- 52. 사내의 최고급여과 최저급여의 차이를 조회한다.
SELECT (MAX(SALARY)-MIN(SALARY)) AS SAL_RELATIVE
  FROM EMPLOYEES
;
-- 53. 102번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) 
  FROM EMPLOYEES
 WHERE MANAGER_ID = 102
;
 
-- 54. 113번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) 
  FROM EMPLOYEES
 WHERE MANAGER_ID = 113
;
-- 55. 'SA_REP' 직무인 직원 중 가장 높은 급여과 가장 낮은 급여를 조회한다.
SELECT MAX(SALARY)
	 , MIN(SALARY)
  FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP'
;
-- 56. 부서아이디별 평균 급여를 조회한다.
SELECT DEPARTMENT_ID 
	 , AVG(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
;
-- 57. 직무아이디별 평균 급여, 최고급여, 최저급여를 조회한다.
SELECT DEPARTMENT_ID 
	 , AVG(SALARY)
	 , MAX(SALARY)
	 , MIN(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
;
  
-- 58. 직무아이디별 사원의 수를 조회한다.
SELECT JOB_ID 
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY JOB_ID 
;
-- 59. 상사아이디별 부하직원의 수를 조회한다. 단, 부하직원이 2명 이하인 경우는 제외한다.
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY MANAGER_ID
 HAVING COUNT(EMPLOYEE_ID) > 2
;
-- 60. 부서번호별 현재 시간으로부터 15년 전 보다 일찍 입사한 사원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID) 
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, -180)
 GROUP BY DEPARTMENT_ID 
;
-- 61. 커미션을 안받는 사원이 근무하는 도시를 조회한다.
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID 
 						 FROM DEPARTMENTS
 						WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
 												  FROM EMPLOYEES
 												 WHERE COMMISSION_PCT IS NULL
 												 )
 						)
;
-- 62. 회사 전체의 평균 급여보다 많이 받는 사원들 중 
--     이름에 'u' 가 포함된 사원과 동일한 부서에서 근무중인 사원들의 모든 정보를 조회한다.

SELECT DISTINCT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
   AND DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						   FROM EMPLOYEES
 						  WHERE FIRST_NAME LIKE '%u%'
)
;
-- 63. 이름이 'REnskE' 인 사원의 급여과 같은 급여를 받는 사원의 모든 정보를 조회한다. 
--     단, 'REnskE' 사원은 조회에서 제외한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE SALARY = (SELECT SALARY 
 				   FROM EMPLOYEES
 				  WHERE FIRST_NAME = 'REnskE')
   AND FIRST_NAME != 'REnskE'
;
-- 64. 평균 급여보다 많이 받는 사원들의 사원번호, 이름, 성, 급여를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
;
-- 65. 평균 급여보다 적게 받는 사원들의 사원번호, 급여, 부서번호를 조회한다.
SELECT EMPLOYEE_ID 
	 , SALARY
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY < (SELECT AVG(SALARY)
 				   FROM EMPLOYEES)
;
-- 66. 가장 많은 급여를 받는 사원의 사원번호, 이름, 급여를 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
 				   FROM EMPLOYEES)
;
-- 67. 자신의 상사보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES a
 WHERE SALARY > (SELECT SALARY 
 				   FROM EMPLOYEES E 
 				  WHERE a.MANAGER_ID = E.EMPLOYEE_ID )
;

SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES M
 	ON E.MANAGER_ID = M.EMPLOYEE_ID 
 WHERE E.SALARY > M.SALARY
;

-- 68. 자신의 상사보다 더 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES a
 WHERE a.HIRE_DATE < (SELECT HIRE_DATE 
 				   FROM EMPLOYEES E 
 				  WHERE a.MANAGER_ID = E.EMPLOYEE_ID )
;
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES M
 	ON E.MANAGER_ID = M.EMPLOYEE_ID 
 WHERE E.HIRE_DATE < M.HIRE_DATE
;
-- 69. 가장 많은 커미션을 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT  < (SELECT MAX(COMMISSION_PCT ) 
 				   			FROM EMPLOYEES)
;
-- 70. 가장 적은 커미션을 받는 사원의 급여과 커미션을 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES a
 WHERE COMMISSION_PCT  < (SELECT MIN(COMMISSION_PCT ) 
 				   			FROM EMPLOYEES)
;
-- 71. 사원이 속한 부서의 평균급여보다 적게 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES a
 WHERE a.SALARY < (SELECT AVG(SALARY) 
 				   FROM EMPLOYEES E 
 				  WHERE a.DEPARTMENT_ID  = E.DEPARTMENT_ID  )
;

SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.EMAIL 
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.EMAIL 
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID 
  FROM EMPLOYEES E
 INNER JOIN (SELECT AVG(E2.SALARY) AS SAL_AVG
 				  , D.DEPARTMENT_ID
			  FROM EMPLOYEES E2
			 INNER JOIN DEPARTMENTS D
			 	ON E2.EMPLOYEE_ID = D.DEPARTMENT_ID 
			 GROUP BY D.DEPARTMENT_ID ) A
	ON E.DEPARTMENT_ID = A.DEPARTMENT_ID
 WHERE SALARY < SAL_AVG
;
-- 72. 50번 부서의 부서장의 이름, 성, 급여를 조회한다.
SELECT FIRST_NAME
	 , LAST_NAME 
	 , SALARY 
  FROM EMPLOYEES 
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID 
 						FROM DEPARTMENTS
 					   WHERE DEPARTMENT_ID = 50)
 ;
-- 73. 사원이 없는 부서명을 조회한다.
-- 사원들이 근무중인 부서의 번호
SELECT E.DEPARTMENT_ID 
  FROM EMPLOYEES E
 ORDER BY E.DEPARTMENT_ID ASC
;

SELECT DEPARTMENT_NAME  
  FROM DEPARTMENTS 
 WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID
  						   	   FROM EMPLOYEES
  						   	  WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL)
;
-- 74. 직무가 변경된 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.EMPLOYEE_ID IN (SELECT DISTINCT jh.EMPLOYEE_ID 
 						   FROM JOB_HISTORY jh)
; 
-- 75. 직무가 변경된적 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.EMPLOYEE_ID NOT IN (SELECT DISTINCT jh.EMPLOYEE_ID 
 						  	   FROM JOB_HISTORY jh)
; 
-- 76. 직무가 가장 많이 변경된 부서의 이름을 조회한다.
SELECT DEPARTMENT_ID
	 , COUNT(EMPLOYEE_ID)
	 , RANK() OVER(ORDER BY COUNT(EMPLOYEE_ID) DESC) AS RANKING -- RANK 순위를 만들겠다 // OVER 정렬기준
  FROM JOB_HISTORY
 GROUP BY DEPARTMENT_ID
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						   FROM (SELECT DEPARTMENT_ID
	 		 						  , RANK() OVER(ORDER BY EMP_CNT DESC) AS RANK
  		  						   FROM (SELECT DEPARTMENT_ID
	 		 		 						  , COUNT(EMPLOYEE_ID) AS EMP_CNT
							  		  	   FROM JOB_HISTORY
							 		 	  GROUP BY DEPARTMENT_ID))
 						  WHERE RANK = 1)
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS 
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
									 , EMP_CNT
									 , ROWNUM AS RNUM
								  FROM(SELECT DEPARTMENT_ID
											, COUNT(EMPLOYEE_ID) AS EMP_CNT
										 FROM JOB_HISTORY
										GROUP BY DEPARTMENT_ID
										ORDER BY EMP_CNT))
						 WHERE RNUM = 1)
;

-- 77. 근무중인 사원이 없는 도시를 조회한다.
SELECT DISTINCT LOCATION_ID   
  FROM DEPARTMENTS 
 WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID
  						   	   FROM EMPLOYEES
  						   	  WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL)
;-- 사원이 없는 부서
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID   
  						 FROM DEPARTMENTS 
						WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID
  						   	   						  FROM EMPLOYEES
  						   	  						 WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL))
    OR LOCATION_ID NOT IN (SELECT LOCATION_ID 
   							 FROM DEPARTMENTS
   							WHERE LOCATION_ID IS NOT NULL
   							 )
;-- 사원이 없는 부서가 있는 도시 + 부서가 없는 도시

SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID NOT IN (SELECT DISTINCT LOCATION_ID   
  						 FROM DEPARTMENTS 
						WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID
  						   	   						  FROM EMPLOYEES
  						   	  						 WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL))
;-- 사원이 있는 부서가 없는 도시
-- 78. 급여가 7000 에서 12000 사이인 사원이 근무중인 도시를 조회한다.												   
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID 
 						 FROM DEPARTMENTS
 						WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 												  FROM EMPLOYEES
 												 WHERE SALARY >= 7000
 												   AND SALARY <= 12000 
 												   AND EMPLOYEES.DEPARTMENT_ID IS NOT NULL
 												)
 					   )
; 
-- 79. 'Seattle' 에서 근무중인 사원의 직무명을 중복없이 조회한다.
SELECT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN (SELECT DISTINCT JOB_ID
 					FROM EMPLOYEES
 				   WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 				   							 FROM DEPARTMENTS
 				   							WHERE LOCATION_ID IN (SELECT LOCATION_ID 
 				   													FROM LOCATIONS 
 				   												   WHERE CITY = 'Seattle'
 				   							) 
 				   							)
 					)
;
-- 80. 부서가 없는 국가명을 조회한다.
SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID NOT IN (SELECT COUNTRY_ID 
 							FROM LOCATIONS
 						   WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID 
 						   						   FROM DEPARTMENTS
 						   						   )
 						   	 AND COUNTRY_ID IS NOT NULL
 						   )
;
-- 81. 'Europe' 에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 						   FROM DEPARTMENTS
 						  WHERE LOCATION_ID IN (SELECT LOCATION_ID 
 						  						  FROM LOCATIONS
 						  						 WHERE COUNTRY_ID IN (SELECT COUNTRY_ID 
 						  						 						FROM COUNTRIES
 						  						 					   WHERE REGION_ID = (SELECT REGION_ID 
 						  						 					   						FROM REGIONS
 						  						 					   					   WHERE REGION_NAME = 'Europe') 
 						  						 					   ) 
 						  						 ) 
 						 )
; 					
-- 82. 'Seattle' 에서 근무중인 사원의 이름, 성, 급여, 부서명 을 조회한다.
SELECT LOCATION_ID
  FROM LOCATIONS
 WHERE CITY = 'Seattle'
;
SELECT DEPARTMENT_ID  
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
  						FROM LOCATIONS
 					   WHERE CITY = 'Seattle')
; 			
SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  
  						   FROM DEPARTMENTS
 						  WHERE LOCATION_ID = (SELECT LOCATION_ID
  												 FROM LOCATIONS
 					   							WHERE CITY = 'Seattle'))
; 					   							
-- 83. 'Seattle' 에서 근무하지 않는 모든 사원의 이름, 성, 급여, 부서명, 도시를 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME
	 , E.SALARY
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  INNER JOIN DEPARTMENTS D 
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID 
 						 FROM EMPLOYEES
 						WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  
  						   						  FROM DEPARTMENTS
 						  						 WHERE LOCATION_ID = (SELECT LOCATION_ID
  												 						FROM LOCATIONS
 					   												   WHERE CITY = 'Seattle')))
; 					   												   
-- 84. 모든 사원들의 이름, 성, 급여, 부서명을 부서번호로 내림차순 정렬하여 조회한다.
SELECT E.FIRST_NAME
	 , E.LAST_NAME
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 ORDER BY D.DEPARTMENT_ID DESC
;
-- 85. 2007년에 직무가 변경된 사원들의 현재 직무명, 부서명, 사원번호, 이름, 성을 조회한다.
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
  FROM EMPLOYEES E , JOBS J, DEPARTMENTS D
 WHERE E.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID
 						   FROM JOB_HISTORY
 						  WHERE START_DATE >= TO_DATE('20070101', 'YYYY-MM-DD')
 						    AND START_DATE < TO_DATE('20080101', 'YYYY-MM-DD'))
   AND E.JOB_ID = J.JOB_ID
   AND E.DEPARTMENT_ID = D.DEPARTMENT_ID 
; 	

SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID 
 WHERE E.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID
 						   FROM JOB_HISTORY
 						  WHERE START_DATE >= TO_DATE('20070101', 'YYYY-MM-DD')
 						    AND START_DATE < TO_DATE('20080101', 'YYYY-MM-DD'))
;
-- 86. 부서장이 없는 부서명 중 첫 글자가 'C' 로 시작하는 부서명을 조회한다.
SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NULL
   AND DEPARTMENT_NAME LIKE 'C%'
;
-- 87. 지역변호가 1000 ~ 1999 사이인 지역내 부서의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID
	 , DEPARTMENT_NAME 
	 , MANAGER_ID 
	 , LOCATION_ID 
  FROM DEPARTMENTS
 WHERE LOCATION_ID >= 1000
   AND LOCATION_ID <= 1999
;
-- 88. 국가 아이디가 'C'로 시작하는 국가의 지역을 모두 조회한다.
SELECT l.CITY  
  FROM LOCATIONS l , COUNTRIES c 
 WHERE c.COUNTRY_ID LIKE 'C%' 
   AND l.COUNTRY_ID = c.COUNTRY_ID 
;
-- 89. 109번 사원의 입사일 부터 1년 동안 입사한 사원의 모든 정보를 조회한다.
SELECT HIRE_DATE
  FROM EMPLOYEES E2 
 WHERE E2.EMPLOYEE_ID = 109
;
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.HIRE_DATE >= (SELECT HIRE_DATE
 						FROM EMPLOYEES E2 
 					   WHERE E2.EMPLOYEE_ID = 109)
   AND E.HIRE_DATE <= ADD_MONTHS((SELECT HIRE_DATE
 						FROM EMPLOYEES E2 
 					   WHERE E2.EMPLOYEE_ID = 109), 12)
;
-- 90. 가장 먼저 입사한 사원의 입사일로부터 2년 동안 입사한사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.HIRE_DATE >= (SELECT MIN(HIRE_DATE) 
 						 FROM EMPLOYEES E2)
   AND E.HIRE_DATE <= ADD_MONTHS((SELECT MIN(HIRE_DATE) 
 						 FROM EMPLOYEES E2), 24)
;
-- 91. 가장 늦게 입사한 사원의 입사일의 1년 보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.HIRE_DATE <ADD_MONTHS( (SELECT MAX(HIRE_DATE) 
 						 FROM EMPLOYEES E2), -12)  
;
-- 92. 사원들이 근무하는 부서명, 이름, 성을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
-- 93. 우편번호가 5자리인 도시에서 근무하는 사원명, 부서명, 도시명, 우편번호를 조회한다.
SELECT E.EMPLOYEE_ID
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
	 , L.POSTAL_CODE 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 WHERE L.POSTAL_CODE LIKE '_____'
; 

SELECT E.EMPLOYEE_ID
	 , D.DEPARTMENT_NAME 
	 , D.CITY  
	 , D.POST 
  FROM EMPLOYEES E
 INNER JOIN(SELECT D.DEPARTMENT_NAME
 				 , D.DEPARTMENT_ID 
 				 , L.CITY AS CITY
 				 , L.POSTAL_CODE AS POST
  			  FROM DEPARTMENTS D
 			 INNER JOIN (SELECT CITY
				 			  , POSTAL_CODE
				 			  , LOCATION_ID
			  			   FROM (SELECT CITY
			 			 	   	      , POSTAL_CODE
			 			 	   	      , LOCATION_ID
			 		  			   FROM LOCATIONS 
			 		 			   WHERE POSTAL_CODE LIKE '_____')) L
 				ON D.LOCATION_ID = L.LOCATION_ID) D
 	ON E.EMPLOYEE_ID = D.DEPARTMENT_ID
;
SELECT *
  FROM (SELECT L.CITY
			 , L.POSTAL_CODE
			 , L.LOCATION_ID
			 , D.DEPARTMENT_ID 
			 , D.DEPARTMENT_NAME 
		  FROM (SELECT CITY
			 , POSTAL_CODE
			 , LOCATION_ID
		  FROM LOCATIONS 
		 WHERE POSTAL_CODE LIKE '_____') L 
		 INNER JOIN DEPARTMENTS D
		 	ON L.LOCATION_ID = D.LOCATION_ID ) L_D
 INNER JOIN EMPLOYEES E
 	ON L_D.DEPARTMENT_ID = E.DEPARTMENT_ID 
;

SELECT *
  FROM (SELECT L.CITY
			 , L.POSTAL_CODE
			 , L.LOCATION_ID
			 , D.DEPARTMENT_ID 
			 , D.DEPARTMENT_NAME 
		  FROM (SELECT CITY
			 		 , POSTAL_CODE
			 		 , LOCATION_ID
		  		  FROM (SELECT CITY
					 		 , POSTAL_CODE
		 	 		 		 , LOCATION_ID
		 	 		 		 , LENGTH(POSTAL_CODE) AS LEN_POST
			 	  		  FROM LOCATIONS)
			 	  		 WHERE LEN_POST = 5) L 
		 INNER JOIN DEPARTMENTS D
		 	ON L.LOCATION_ID = D.LOCATION_ID ) L_D
 INNER JOIN EMPLOYEES E
 	ON L_D.DEPARTMENT_ID = E.DEPARTMENT_ID 
;

-- 94. 부서장이 있는 부서명 중 첫 글자가 'S' 로 시작하는 부서에서 근무중인 사원의 
--     이름과 직무명, 부서명을 조회한다.
SELECT E.FIRST_NAME
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 WHERE D.MANAGER_ID IS NOT NULL
   AND D.DEPARTMENT_NAME LIKE 'S%'
;
-- 95. 90, 60, 100번 부서에서 근무중인 사원의 이름, 성, 부서명을 조회한다.
SELECT E.FIRST_NAME
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE D.DEPARTMENT_ID IN (90,60,100)
;
-- 96. 부서명이 5글자 미만인 부서에서 근무중인 사원의 이름, 부서명을 조회한다.
SELECT E.FIRST_NAME
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE D.DEPARTMENT_NAME IN (SELECT D2.DEPARTMENT_NAME
 							   FROM DEPARTMENTS D2 
 							  GROUP BY D2.DEPARTMENT_NAME
 							 HAVING LENGTH(D2.DEPARTMENT_NAME ) < 5)
; 							 

SELECT E.FIRST_NAME
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE D.DEPARTMENT_NAME NOT LIKE '_____%'
;
-- 97. 도시명에 띄어쓰기 " " 가 포함된 도시에서 근무중인 사원들의 부서명, 도시명, 사원명을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , L.CITY 
	 , E.FIRST_NAME
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 WHERE L.CITY LIKE '% %'
;
-- 98. 우편번호에 공백이 없는 도시에서 근무하는 사원의 이름, 부서명, 우편번호를 조회한다.
SELECT E.FIRST_NAME
	 , D.DEPARTMENT_NAME 
	 , L.POSTAL_CODE
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 WHERE L.POSTAL_CODE NOT IN (SELECT L2.POSTAL_CODE
 						   FROM LOCATIONS L2
 						  WHERE L2.POSTAL_CODE LIKE '% %')
;
SELECT E.FIRST_NAME
	 , D.DEPARTMENT_NAME 
	 , L.POSTAL_CODE
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 WHERE L.POSTAL_CODE NOT LIKE '% %'
;
-- 99. "주"가 없는 도시에서 근무하는 사원의 이름, 도시를 조회한다.
SELECT E.FIRST_NAME
	 , L.CITY
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON L.STATE_PROVINCE IS NULL
   AND D.LOCATION_ID = L.LOCATION_ID
;
-- 100. 사원들의 사원번호, 이름, 성, 상사의 사원번호, 상사의 이름, 상사의 성을 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.MANAGER_ID 
	 , E2.FIRST_NAME AS MANAGER_NAME
	 , E2.LAST_NAME AS MANAGER_LAST_NAME
  FROM EMPLOYEES E 
 INNER JOIN EMPLOYEES E2 
 	ON E.MANAGER_ID = E2.EMPLOYEE_ID
; 	
-- 101. 직무가 변경된 사원의 과거 직무명과 현재 직무명을 조회한다.
SELECT *
  FROM JOB_HISTORY JH 
;
SELECT
	E2.EMPLOYEE_ID,
	J2.JOB_TITLE
FROM
	JOB_HISTORY JH
INNER JOIN EMPLOYEES E2
 	ON JH.EMPLOYEE_ID = E2.EMPLOYEE_ID
INNER JOIN JOBS J2 
 	ON J2.JOB_ID = JH.JOB_ID
;	  	
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE AS PRESENT
	 , J_PAST.JOB_TITLE  AS PAST
  FROM EMPLOYEES E
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN JOB_HISTORY JH 
 	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 INNER JOIN JOBS J_PAST
	ON J_PAST.JOB_ID = JH.JOB_ID 
 ;
-- 102. 가장 적은 급여를 받는 사원의 부서명, 이름, 성, 급여, 부서장사원번호를 조회한다.
SELECT D.DEPARTMENT_NAME
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , E.MANAGER_ID 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.SALARY = (SELECT MIN(E2.SALARY)
 					  FROM EMPLOYEES E2 )
; 		
-- 103. 부서명별 사원의 수를 조회한다.
SELECT COUNT(E.EMPLOYEE_ID )
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME 
;
-- 104. 대륙명별 사원의 수를 조회한다.
SELECT COUNT(E.EMPLOYEE_ID )
	 , R.REGION_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C 
 	ON L.COUNTRY_ID = C.COUNTRY_ID
 INNER JOIN REGIONS R 
 	ON C.REGION_ID = R.REGION_ID
 GROUP BY R.REGION_NAME 
;
-- 105. 직무명별 최소급여를 조회한다.
SELECT J.JOB_TITLE 	
	 , J.MIN_SALARY 
  FROM JOBS J 
;
SELECT J.JOB_TITLE  
	 , MIN(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE 
;
-- 106. 부서명별 최대급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , MIN(E.SALARY )
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
;
-- 107. 직무명별 평균급여를 평균급여순으로 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE  
	 , AVG(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE 
 ORDER BY AVG(E.SALARY) ASC
;
-- 108. 부서명별 평균급여를 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , AVG(E.SALARY )
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
 ORDER BY AVG(E.SALARY) DESC
;
-- 109. 부서명별 급여의 합을 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , SUM(E.SALARY )
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
 ORDER BY SUM(E.SALARY) DESC
;
-- 110. 직무명별 사원의 수를 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE  
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY J.JOB_TITLE 
 ORDER BY AVG(E.EMPLOYEE_ID) ASC
;
-- 111. 직무명, 부서명 별 사원 수, 평균급여를 조회한다.
SELECT J.JOB_TITLE
	 , D.DEPARTMENT_NAME
	 , COUNT(E.EMPLOYEE_ID )
	 , AVG(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME 
 		, J.JOB_TITLE
;

SELECT J.JOB_TITLE  
	 , COUNT(E.EMPLOYEE_ID)
	 , AVG(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN (SELECT D2.DEPARTMENT_NAME AS DEPT_NAME
	 , COUNT(E2.EMPLOYEE_ID ) AS DEPT_CNT
	 , AVG(E2.SALARY ) AS DEPT_AVG
  FROM EMPLOYEES E2 
 INNER JOIN DEPARTMENTS D2 
 	ON E2.DEPARTMENT_ID = D2.DEPARTMENT_ID
 GROUP BY D2.DEPARTMENT_NAME )
 	ON D.DEPARTMENT_NAME = DEPT_NAME 
 GROUP BY J.JOB_TITLE 
;

-- 112. 도시별 사원 수를 조회한다.
SELECT L.CITY 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY L.CITY
;
-- 113. 국가별 사원 수, 최대급여, 최소급여를 조회한다.
SELECT C.COUNTRY_NAME 
	 , COUNT(E.EMPLOYEE_ID)
	 , MAX(SALARY)
	 , MIN(SALARY)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C 
 	ON L.COUNTRY_ID = C.COUNTRY_ID
 GROUP BY C.COUNTRY_NAME 
; 
-- 114. 국가별로 급여가 5000 이상인 사원의 수를 조회한다.
SELECT C.COUNTRY_NAME 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C 
 	ON L.COUNTRY_ID = C.COUNTRY_ID
 WHERE E.SALARY >= 5000
 GROUP BY C.COUNTRY_NAME 
; 
-- 115. 부서명, 직무명 별 평균 급여를 조회한다.
SELECT DISTINCT J.JOB_TITLE
	 , D.DEPARTMENT_NAME
	 , AVG(E.SALARY)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME 
 		, J.JOB_TITLE
;
-- 116. 도시명, 직무명 별 사원의 수를 조회한다.
SELECT L.CITY
	 , COUNT(E.EMPLOYEE_ID)
	 , J.JOB_TITLE 
	 , COUNT(E2.EMPLOYEE_ID)
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN LOCATIONS L 
	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN EMPLOYEES E2 
 	ON E2.JOB_ID = J.JOB_ID 
 GROUP BY L.CITY 
 	 , J.JOB_TITLE
;
-- 117. 부서명, 직무명 별 평균 급여 중 가장 작은 평균급여를 받는 부서명, 직무명을 조회한다.

SELECT DEPARTMENT_NAME
	 , JOB_TITLE
  FROM (SELECT DEPARTMENT_NAME
			 , JOB_TITLE
			 , AVG_SALARY
			 , RANK() OVER ( ORDER BY AVG_SALARY ASC ) AS RANK
		  FROM (SELECT D.DEPARTMENT_NAME
					 , J.JOB_TITLE
					 , AVG(SALARY) AS AVG_SALARY
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
				    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
				 INNER JOIN JOBS J
				 	ON E.JOB_ID = J.JOB_ID
				 GROUP BY D.DEPARTMENT_NAME
				 	 , J.JOB_TITLE))
 WHERE RANK = 1
;

SELECT DEPARTMENT_NAME
			 , JOB_TITLE 
  FROM (SELECT DEPARTMENT_NAME
			 , JOB_TITLE 
			 , SAL_AVG
			 , RANK() OVER(ORDER BY SAL_AVG ASC) AS SAL_RNK
		  FROM (SELECT D.DEPARTMENT_NAME
					 , J.JOB_TITLE 
					 , AVG(SALARY) AS SAL_AVG
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
				 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
				 INNER JOIN JOBS J
				 	ON E.JOB_ID = J.JOB_ID
				 GROUP BY D.DEPARTMENT_NAME 
				 	 , J.JOB_TITLE))
 WHERE SAL_RNK = 1				 	 
; 	


SELECT DEPARTMENT_NAME
	 , JOB_TITLE
  FROM (SELECT DEPARTMENT_NAME
			 , JOB_TITLE
			 , ROWNUM AS RNUM
		 FROM (SELECT D.DEPARTMENT_NAME 
					, J.JOB_TITLE 
					, AVG(SALARY) AS SAL_AVG
				 FROM EMPLOYEES E
				INNER JOIN DEPARTMENTS D
				   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
				INNER JOIN JOBS J
				   ON E.JOB_ID = J.JOB_ID
				GROUP BY D.DEPARTMENT_NAME 
				 	, J.JOB_TITLE 
				ORDER BY SAL_AVG ASC))
 WHERE RNUM = 1				
; 	 
-- 118. 대륙명별 사원 수를 대륙명으로 오름차순 정렬하여 조회한다.
SELECT R.REGION_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
  	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
 	ON C.REGION_ID = R.REGION_NAME
 GROUP BY R.REGION_NAME 
;
-- 119. 직무명별 최대급여보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , EMAIL
	 , PHONE_NUMBER 
	 , HIRE_DATE 
	 , JOB_ID 
	 , SALARY 
	 , COMMISSION_PCT 
	 , MANAGER_ID 
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
  WHERE SALARY > (SELECT MAX_SALARY
  					FROM JOBS J
  				   WHERE J.JOB_ID  = E.JOB_ID )
;

SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN JOBS J
	ON E.JOB_ID = J.JOB_ID 
 WHERE E.SALARY > J.MAX_SALARY 
;
-- 120. 입사연도별 최소급여를 조회한다.
SELECT HIRE_YEAR
	 , MIN(SALARY)
  FROM(SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR
	 		, SALARY
  		 FROM EMPLOYEES)
 GROUP BY HIRE_YEAR
 ORDER BY HIRE_YEAR ASC
;
-- 121. 사원 이름의 글자수 별 사원의 수를 조회한다.
SELECT E.CNT
	 , COUNT(E.EMPLOYEE_ID)
  FROM (SELECT LENGTH(FIRST_NAME) AS CNT
  			 , EMPLOYEE_ID
  		  FROM EMPLOYEES) E
 GROUP BY E.CNT
 ORDER BY E.CNT ASC
;
-- 122. 사원 성의 글자수 별 사원의 수를 조회한다.
SELECT E.CNT
	 , COUNT(E.EMPLOYEE_ID)
  FROM (SELECT LENGTH(LAST_NAME) AS CNT
  			 , EMPLOYEE_ID
  		  FROM EMPLOYEES) E
 GROUP BY E.CNT
 ORDER BY E.CNT ASC
;
-- 123. 커미션을 포함한 급여가 10000 이상인 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN (SELECT EMPLOYEE_ID
 				  , SALARY + (SALARY * COMMISSION_PCT) AS SALARY_PCT
 			   FROM EMPLOYEES
 			  WHERE COMMISSION_PCT IS NOT NULL)E2
 	ON E.EMPLOYEE_ID = E2.EMPLOYEE_ID 
 WHERE E2.SALARY_PCT >= 10000
;

SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM (SELECT EMPLOYEE_ID
			 , FIRST_NAME
			 , LAST_NAME 
			 , EMAIL
			 , PHONE_NUMBER 
			 , HIRE_DATE 
			 , JOB_ID 
			 , SALARY 
			 , SALARY + (SALARY * NVL(COMMISSION_PCT,0)) AS SALARY_PCT
			 , COMMISSION_PCT 
			 , MANAGER_ID 
			 , DEPARTMENT_ID
	 	  FROM EMPLOYEES) E
 WHERE E.SALARY_PCT >= 10000
;

SELECT *
  FROM EMPLOYEES
 WHERE SALARY + (SALARY * COMMISSION_PCT) >= 10000
;
-- 124. 국가 아이디의 첫 글자와 국가명의 첫 글자가 다른 모든 국가를 조회한다.
SELECT C.COUNTRY_ID
	 , C.COUNTRY_NAME
  FROM (SELECT COUNTRY_NAME
  			 , COUNTRY_ID
  		  FROM COUNTRIES
  		 WHERE SUBSTR(COUNTRY_NAME,1,1) != SUBSTR(COUNTRY_ID, 1,1)) C
;
-- 124-2 국가 아이디의 첫 글자와 국가명의 첫 글자가 같은 국가의 이름, 국가아이디, 해당 국가의 부서 이름을 조회한다.
SELECT C.COUNTRY_NAME
	 , C.COUNTRY_ID 
	 , D.DEPARTMENT_NAME 
  FROM (SELECT COUNTRY_NAME
  			 , COUNTRY_ID 
  			 , REGION_ID
  			 , SUBSTR(COUNTRY_NAME,1,1) AS NAME_LETTER
  			 , SUBSTR(COUNTRY_ID, 1,1) AS ID_LETTER	
  		  FROM (SELECT COUNTRY_NAME
		  			 , COUNTRY_ID 
		  			 , REGION_ID
		  			 , SUBSTR(COUNTRY_NAME,1,1) AS NAME_LETTER
		  			 , SUBSTR(COUNTRY_ID, 1,1) AS ID_LETTER	
		  		  FROM COUNTRIES)
  		 WHERE NAME_LETTER = ID_LETTER) C
 INNER JOIN LOCATIONS L
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN DEPARTMENTS D 
 	ON L.LOCATION_ID = D.LOCATION_ID
;
-- 125. 이름의 첫 번째 글자별 평균급여를 조회한다.
SELECT E.FIRST_LETTER 
	 , AVG(E.SALARY) AS AVERAGE
  FROM (SELECT SUBSTR(FIRST_NAME,1,1) AS FIRST_LETTER
  			 , SALARY
  		  FROM EMPLOYEES) E
 GROUP BY E.FIRST_LETTER 
 ORDER BY E.FIRST_LETTER 
;
-- 126. 많은 급여를 받는 10명을 조회한다.
SELECT SALARY
	 , EMPLOYEE_ID
	 , ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS SAL_ROW
  FROM EMPLOYEES
;
SELECT EMPLOYEE_ID
  FROM (SELECT SALARY
	 		 , EMPLOYEE_ID
	 		 , ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS SAL_ROW
  		  FROM EMPLOYEES)
 WHERE SAL_ROW <= 10
;

SELECT FIRST_NAME
	 , EMPLOYEE_ID
	 , SALARY
  FROM (SELECT FIRST_NAME
			 , EMPLOYEE_ID
			 , SALARY
			 , ROWNUM AS RNUM
		  FROM (SELECT EMPLOYEE_ID
					 , FIRST_NAME
					 , SALARY
				  FROM EMPLOYEES
				 ORDER BY SALARY ASC))
 WHERE RNUM <= 10				 
;
-- 127. 많은 급여를 받는 사원 중 11번 째 부터 20번째를 조회한다.
SELECT EMPLOYEE_ID
  FROM (SELECT SALARY
	 		 , EMPLOYEE_ID
	 		 , ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS SAL_ROW
  		  FROM EMPLOYEES)
 WHERE SAL_ROW > 10
   AND SAL_ROW <= 20
;

SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , SALARY
  FROM (SELECT EMPLOYEE_ID 
			 , FIRST_NAME 
			 , SALARY
			 , ROWNUM AS RNUM
		  FROM (SELECT EMPLOYEE_ID
					 , FIRST_NAME
					 , SALARY
				  FROM EMPLOYEES 
				 ORDER BY SALARY DESC)
		 WHERE ROWNUM <= 20)
 WHERE RNUM >= 11				 
;

-- 128. 가장 적은 급여를 받는 중 90번 째 부터 100번째를 조회한다.
SELECT EMPLOYEE_ID
  FROM (SELECT SALARY
	 		 , EMPLOYEE_ID
	 		 , ROW_NUMBER() OVER(ORDER BY SALARY ASC) AS SAL_ROW
  		  FROM EMPLOYEES)
 WHERE SAL_ROW >= 90
   AND SAL_ROW < 101
;
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , SALARY
  FROM (SELECT EMPLOYEE_ID 
			 , FIRST_NAME 
			 , SALARY
			 , ROWNUM AS RNUM
		  FROM (SELECT EMPLOYEE_ID
					 , FIRST_NAME
					 , SALARY
				  FROM EMPLOYEES 
				 ORDER BY SALARY ASC)
		 WHERE ROWNUM <= 100)
 WHERE RNUM >= 90				 
;

-- 129. 가장 적은 급여를 받는 사원의 상사명, 부서명을 조회한다.					
SELECT MANAGER.FIRST_NAME
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN EMPLOYEES MANAGER
 	ON E.MANAGER_ID = MANAGER.EMPLOYEE_ID 
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.SALARY = (SELECT MIN(E2.SALARY)
 					 FROM EMPLOYEES E2 )
; 					
-- 130. 'PU_CLERK' 직무인 2번째 부터 5번째 사원의 부서명, 직무명을 조회한다.
SELECT D.DEPARTMENT_NAME
	 , J.JOB_TITLE 
  FROM (SELECT FIRST_NAME
			 , DEPARTMENT_ID
			 , JOB_ID
			 , ROWNUM AS RNUM
		  FROM EMPLOYEES
		 WHERE JOB_ID = 'PU_CLERK') E
 INNER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
  	ON E.JOB_ID = J.JOB_ID
 WHERE RNUM >= 2
   AND RNUM <= 5
;
-- 131. 월별 최대급여 중 2번째 부터 4번째 데이터만 조회한다.

SELECT HIRE_MONTH
	 , MX_SALARY
  FROM (SELECT HIRE_MONTH
  			 , MX_SALARY
	 		 , ROW_NUMBER() OVER(ORDER BY MX_SALARY DESC) AS ROW_NUM
  		  FROM (SELECT MAX(SALARY) AS MX_SALARY
	 		 		 , HIRE_MONTH
  		  		  FROM (SELECT SALARY
	 		 		 		 , TO_CHAR(HIRE_DATE, 'MM') AS HIRE_MONTH
  		  		  		  FROM EMPLOYEES)
 		 		 GROUP BY HIRE_MONTH))
 WHERE ROW_NUM > 1
   AND ROW_NUM < 5
; 		 		

SELECT HIRE_MONTH
	 , MX_SALARY
  FROM (SELECT HIRE_MONTH
			 , MX_SALARY
			 , ROWNUM AS RNUM
		  FROM (SELECT HIRE_MONTH
					 , MAX(SALARY) AS MX_SALARY
				  FROM (SELECT SALARY
							 , TO_CHAR(HIRE_DATE, 'MM') AS HIRE_MONTH
						  FROM EMPLOYEES)
				 GROUP BY HIRE_MONTH)
		 WHERE ROWNUM <= 4)
 WHERE RNUM >= 2
;
-- 132. 근무중인 사원이 가장 많은 도시와 사원의 수를 조회한다.  

SELECT E.CITY
	 , E.EMP_CNT
  FROM (SELECT CITY
	 		 , EMP_CNT
  		  FROM (SELECT CITY
	 		 		 , DENSE_RANK() OVER(ORDER BY EMP_CNT DESC) AS EMP_RNK
	 		 		 , EMP_CNT
  		 		  FROM (SELECT L.CITY 
	 		 				 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  		  		 		  FROM EMPLOYEES E
 		 			 	 INNER JOIN DEPARTMENTS D
 				   			ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 				   		 INNER JOIN LOCATIONS L
 				   			ON D.LOCATION_ID = L.LOCATION_ID 
 		 				 GROUP BY L.CITY ))
 		  WHERE EMP_RNK = 1) E	
;

SELECT CITY
	 , EMP_CNT
  FROM (SELECT CITY
			 , EMP_CNT
		  FROM (SELECT L.CITY 
					 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
				 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
				 INNER JOIN LOCATIONS L
				 	ON D.LOCATION_ID = L.LOCATION_ID
				 GROUP BY L.CITY)
		 ORDER BY EMP_CNT DESC)
 WHERE ROWNUM = 1
;
-- 133. 사원의 수가 가장 많은 부서명, 사원의 수를 조회한다.

SELECT DEPARTMENT_NAME
	 , EMP_CNT
  FROM (SELECT DEPARTMENT_NAME
	 		 , EMP_CNT
	 		 , DENSE_RANK() OVER(ORDER BY EMP_CNT DESC) AS EMP_RNK
  		  FROM (SELECT D.DEPARTMENT_NAME
	 		 		 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  		  		  FROM EMPLOYEES E
 		 		  INNER JOIN DEPARTMENTS D
 					 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 		 		  GROUP BY D.DEPARTMENT_NAME))
 WHERE EMP_RNK = 1
;

SELECT DEPARTMENT_NAME
	 , EMP_CNT
  FROM (SELECT DEPARTMENT_NAME
			 , EMP_CNT
		  FROM (SELECT D.DEPARTMENT_NAME 
					 , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
				  FROM DEPARTMENTS D
				 INNER JOIN EMPLOYEES E
				 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
				 GROUP BY D.DEPARTMENT_NAME )
		 ORDER BY EMP_CNT DESC)
 WHERE ROWNUM = 1
; 
-- 134. 가장 많은 부서가 있는 도시를 조회한다.
SELECT CITY
  FROM (SELECT CITY
	 		 , RANK() OVER(ORDER BY CNT DESC) AS RNK
  		  FROM (SELECT L.CITY
	 		 		 , COUNT(D.DEPARTMENT_ID) AS CNT
  				  FROM LOCATIONS L
 				 INNER JOIN DEPARTMENTS D
 					ON L.LOCATION_ID = D.LOCATION_ID
 			  GROUP BY CITY))
 WHERE RNK = 1
;

SELECT CITY
	 , DEPT_CNT
  FROM (SELECT CITY
			 , DEPT_CNT
		  FROM (SELECT L.CITY 
					 , COUNT(D.DEPARTMENT_ID ) AS DEPT_CNT
				  FROM LOCATIONS L
				 INNER JOIN DEPARTMENTS D
				 	ON L.LOCATION_ID = D.LOCATION_ID 
				 GROUP BY L.CITY )
		 ORDER BY DEPT_CNT DESC)
 WHERE ROWNUM = 1		 
;
-- 135. 가장 많은 사원이 있는 부서의 국가명을 조회한다.
SELECT L.COUNTRY_ID
  FROM LOCATIONS L
 INNER JOIN (SELECT LOCATION_ID
  			   FROM (SELECT LOCATION_ID
	 		 			  , DENSE_RANK() OVER(ORDER BY EMP_CNT DESC) AS EMP_RNK
  		 			   FROM (SELECT D.LOCATION_ID 
	 		 			 		  , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  		  		 			   FROM EMPLOYEES E
 		 					  INNER JOIN DEPARTMENTS D
 				   				 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 		 					  GROUP BY D.LOCATION_ID ))
 			  WHERE EMP_RNK = 1) E	
 	ON L.LOCATION_ID = E.LOCATION_ID 
;
SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID = (SELECT L.COUNTRY_ID
			  		   FROM LOCATIONS L
			 		  WHERE L.LOCATION_ID = (SELECT LOCATION_ID
						  		 	   		   FROM (SELECT LOCATION_ID
							 		 			  		  , DENSE_RANK() OVER(ORDER BY EMP_CNT DESC) AS EMP_RNK
						  		 			   		   FROM (SELECT D.LOCATION_ID 
							 		 			 		  		  , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
						  		  		 			   		   FROM EMPLOYEES E
						 		 					  		  INNER JOIN DEPARTMENTS D
						 				   				 		 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
						 		 					  GROUP BY D.LOCATION_ID ))
						 			  		  WHERE EMP_RNK = 1))
;

SELECT COUNTRY_NAME
  FROM COUNTRIES
 WHERE COUNTRY_ID = (SELECT COUNTRY_ID
 					   FROM LOCATIONS 
					  WHERE LOCATION_ID = (SELECT LOCATION_ID
										     FROM DEPARTMENTS
										    WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
																     FROM (SELECT DEPARTMENT_ID
																			    , EMP_CNT
																		     FROM (SELECT D.DEPARTMENT_ID
																					    , COUNT(E.EMPLOYEE_ID) AS EMP_CNT
																				     FROM DEPARTMENTS D
																				    INNER JOIN EMPLOYEES E
																				 	   ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
																				    GROUP BY D.DEPARTMENT_ID )	
																		    ORDER BY EMP_CNT DESC)
																    WHERE ROWNUM = 1)))
 ;
-- 136. 'Europe' 에서 가장 많은 사원들이 있는 부서명을 조회한다.					
SELECT DEPARTMENT_NAME 
	 , RANK() OVER(ORDER BY CNT DESC)
  FROM (SELECT DEPARTMENT_NAME
			 , COUNT(EMPLOYEE_ID) AS CNT
		  FROM EMPLOYEES E
		 INNER JOIN (SELECT DEPARTMENT_ID
						  , DEPARTMENT_NAME
					   FROM DEPARTMENTS
					  WHERE LOCATION_ID IN (SELECT LOCATION_ID
											  FROM LOCATIONS 
											 WHERE COUNTRY_ID  IN (SELECT COUNTRY_ID
																	 FROM COUNTRIES
																	WHERE REGION_ID = (SELECT REGION_ID
																	 				 	 FROM REGIONS
																	 					WHERE REGION_NAME = 'Europe')))) D
			ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		 GROUP BY DEPARTMENT_NAME)
;
SELECT DEPARTMENT_NAME
  FROM (SELECT DEPARTMENT_NAME 
			 , RANK() OVER(ORDER BY CNT DESC) AS RNK
		  FROM (SELECT DEPARTMENT_NAME
					 , COUNT(EMPLOYEE_ID) AS CNT
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
					ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
				 WHERE D.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
										     FROM DEPARTMENTS
										    WHERE LOCATION_ID IN (SELECT LOCATION_ID
																    FROM LOCATIONS 
																   WHERE COUNTRY_ID  IN (SELECT COUNTRY_ID
																						   FROM COUNTRIES
																						  WHERE REGION_ID = (SELECT REGION_ID
																						 				 	   FROM REGIONS
																						 					  WHERE REGION_NAME = 'Europe'))))
				 GROUP BY DEPARTMENT_NAME))
 WHERE RNK = 1
;

SELECT DEPARTMENT_NAME
  FROM (SELECT DEPARTMENT_NAME
			 , CNT
		  FROM (SELECT DEPARTMENT_NAME
					 , COUNT(EMPLOYEE_ID) AS CNT
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
					ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
				 WHERE D.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
											FROM DEPARTMENTS
										   WHERE LOCATION_ID IN (SELECT LOCATION_ID
																			FROM LOCATIONS 
																		   WHERE COUNTRY_ID  IN (SELECT COUNTRY_ID
																								FROM COUNTRIES
																							   WHERE REGION_ID = (SELECT REGION_ID
																										 		 FROM REGIONS
																										 		WHERE REGION_NAME = 'Europe'))))
				 GROUP BY DEPARTMENT_NAME)
		 ORDER BY CNT DESC)
 WHERE ROWNUM = 1
;

-- 137. 100번 사원의 모든 부하직원을 계층조회한다. 단, LEVEL이 4인 사원은 제외한다.
 SELECT E.EMPLOYEE_ID
   FROM EMPLOYEES E
  WHERE LEVEL != 4
  START WITH E.EMPLOYEE_ID = 100
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
;
-- 138. 101번 사원의 모든 부하직원 들의 이름, 성, 상사사원번호, 상사사원명을 계층 조회한다.
 SELECT E.EMPLOYEE_ID  
 	  ,	E.FIRST_NAME
 	  , E.LAST_NAME 
 	  , E.MANAGER_ID 
 	  , LEVEL
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID = 101
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
;
-- 139. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호, 상사사원명을 계층 조회한다.
 SELECT E.FIRST_NAME
 	  , E.LAST_NAME 
 	  , E.MANAGER_ID 
 	  , LEVEL
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID = 114
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID
;
-- 140. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호, 상사사원명을 역순으로 계층 조회한다.
 SELECT E.FIRST_NAME
 	  , E.LAST_NAME 
 	  , E.MANAGER_ID 
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID = 114
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID
 ORDER BY LEVEL DESC
;
-- 141. 부서별 사원의 수를 조인을 이용해 다음과 같이 조회한다."부서명 (사원의 수)"
SELECT D.DEPARTMENT_NAME || ' (' ||  COUNT(E.EMPLOYEE_ID)|| ')' AS RESULT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME
;
-- 142. 부서별 사원의 수를 스칼라쿼리를 이용해 다음과 같이 조회한다. "부서명 (사원의 수)"
SELECT DEPARTMENT_NAME || ' (' 
	|| (SELECT COUNT(E.EMPLOYEE_ID)
		  FROM EMPLOYEES E 
		 WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID ) || ')' AS RESULT
  FROM DEPARTMENTS D
;
-- 143. 사원의 정보를 다음과 같이 조회한다. "사원번호 번 사원의 이름은 성이름 입니다."
SELECT EMPLOYEE_ID || '번 사원의 이름은 ' || FIRST_NAME || ' ' || LAST_NAME || ' 입니다.' AS RESULT
  FROM EMPLOYEES
 ORDER BY EMPLOYEE_ID ASC
;  
-- 144. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. 
--      "사원번호 번 사원의 상사명은 상사명 입니다."
SELECT EMPLOYEE_ID || '번 사원의 상사명은 ' 
	|| (SELECT M.FIRST_NAME || ' ' || M.LAST_NAME 
		  FROM EMPLOYEES M 
		 WHERE E.MANAGER_ID = M.EMPLOYEE_ID) || '입니다.'  AS RESULT
  FROM EMPLOYEES E
 ORDER BY EMPLOYEE_ID ASC
;
-- 145. 사원의 정보를 조인을 이용해 다음고 같이 조회한다. "사원명 (직무명)"
SELECT '"' || E.FIRST_NAME || ' ' || E.LAST_NAME  || ' (' || J.JOB_TITLE || ')"' AS RESULT
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
;
-- 146. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원명 (직무명)"
SELECT '"' || E.FIRST_NAME || ' ' || E.LAST_NAME  || ' (' 
	|| (SELECT J.JOB_TITLE 
		  FROM JOBS J 
		 WHERE E.JOB_ID = J.JOB_ID ) || ')"' AS RESULT
  FROM EMPLOYEES E 
;
-- 147. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서명을 조회한다.

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
								  FROM (SELECT NVL(DEPARTMENT_ID, 0) AS DEPARTMENT_ID
											 , MAX(J.SAL_SUB) AS SAL_SUB
										  FROM EMPLOYEES E
										 INNER JOIN (SELECT JOB_ID
														  , (MAX_SALARY - MIN_SALARY) AS SAL_SUB
													   FROM JOBS) J
											ON E.JOB_ID = J.JOB_ID 
										 GROUP BY DEPARTMENT_ID)
								 ORDER BY SAL_SUB DESC)
						 WHERE ROWNUM = 1)
;

SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
									 , RANK() OVER(ORDER BY SAL_SUB DESC) AS SAL_RNK
								  FROM (SELECT NVL(DEPARTMENT_ID, 0) AS DEPARTMENT_ID
											 , MAX(J.SAL_SUB) AS SAL_SUB
										  FROM EMPLOYEES E
										 INNER JOIN (SELECT JOB_ID
														  , (MAX_SALARY - MIN_SALARY) AS SAL_SUB
													   FROM JOBS) J
											ON E.JOB_ID = J.JOB_ID 
										 GROUP BY DEPARTMENT_ID))
						 WHERE SAL_RNK = 1)
;					 
-- 148. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서에서 근무하는 사원들의 직무명을 
--      중복없이 조회한다.
SELECT JOB_ID
  FROM EMPLOYEES 
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT DEPARTMENT_ID
									 , RANK() OVER(ORDER BY SAL_SUB DESC) AS SAL_RNK
								  FROM (SELECT NVL(DEPARTMENT_ID, 0) AS DEPARTMENT_ID
											 , MAX(J.SAL_SUB) AS SAL_SUB
										  FROM EMPLOYEES E
										 INNER JOIN (SELECT JOB_ID
														  , (MAX_SALARY - MIN_SALARY) AS SAL_SUB
													   FROM JOBS) J
											ON E.JOB_ID = J.JOB_ID 
										 GROUP BY DEPARTMENT_ID))
						 WHERE SAL_RNK = 1)
;
SELECT DISTINCT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN (SELECT JOB_ID
				    FROM EMPLOYEES 
				   WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
										    FROM (SELECT DEPARTMENT_ID
													   , RANK() OVER(ORDER BY SAL_SUB DESC) AS SAL_RNK
												    FROM (SELECT NVL(DEPARTMENT_ID, 0) AS DEPARTMENT_ID
															   , MAX(J.SAL_SUB) AS SAL_SUB
														    FROM EMPLOYEES E
														   INNER JOIN (SELECT JOB_ID
																		    , (MAX_SALARY - MIN_SALARY) AS SAL_SUB
																	     FROM JOBS) J
															  ON E.JOB_ID = J.JOB_ID 
														   GROUP BY DEPARTMENT_ID))
										   WHERE SAL_RNK = 1))
;							

SELECT DISTINCT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN (SELECT JOB_ID
				   FROM EMPLOYEES
				  WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
										   FROM (SELECT DEPARTMENT_ID
													  , RANK() OVER(ORDER BY SAL_SUB DESC) AS SAL_RNK
												   FROM (SELECT NVL(DEPARTMENT_ID, 0) AS DEPARTMENT_ID
															  , MAX(J.SAL_SUB) AS SAL_SUB
														   FROM EMPLOYEES E
														  INNER JOIN (SELECT JOB_ID
																		   , (MAX_SALARY - MIN_SALARY) AS SAL_SUB
																	    FROM JOBS) J
															 ON E.JOB_ID = J.JOB_ID 
														  GROUP BY DEPARTMENT_ID))
										  WHERE SAL_RNK = 1))
;						
-- 149. 부하직원이 없는 사원의 모든 정보를 조회한다.
SELECT COUNT(E.EMPLOYEE_ID)
	 , E.MANAGER_ID 
  FROM EMPLOYEES E 
 GROUP BY E.MANAGER_ID
 ORDER BY E.MANAGER_ID ASC
;
SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME
	 , E.LAST_NAME 
	 , E.EMAIL
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.JOB_ID 
	 , E.SALARY 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E 
 WHERE E.EMPLOYEE_ID NOT IN (SELECT DISTINCT E2.MANAGER_ID 
 						  	   FROM EMPLOYEES E2
 						  	  WHERE E2.MANAGER_ID IS NOT NULL)
;
-- 150. 사원번호가 100번인 사원의 사원번호, 이름과 
--      사원번호로 내림차순 정렬된 사원의 사원번호, 이름을 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
  FROM EMPLOYEES 
 WHERE EMPLOYEE_ID = 100
 UNION
SELECT EMP.EMPLOYEE_ID
	 , EMP.FIRST_NAME
  FROM (SELECT EMP.EMPLOYEE_ID
			 , EMP.FIRST_NAME
		  FROM EMPLOYEES EMP
		 WHERE EMPLOYEE_ID != 100
		 ORDER BY EMPLOYEE_ID DESC) EMP
;

SELECT EMPLOYEE_ID
	 , FIRST_NAME
  FROM EMPLOYEES 
 WHERE EMPLOYEE_ID = 100
 UNION ALL
SELECT EMP.EMPLOYEE_ID
	 , EMP.FIRST_NAME
  FROM (SELECT EMP.EMPLOYEE_ID
			 , EMP.FIRST_NAME
		  FROM EMPLOYEES EMP
		 WHERE EMPLOYEE_ID != 100
		 ORDER BY EMPLOYEE_ID DESC) EMP
;
/*조회 예
--------------------
100    StEvEn
206    William
205    ShEllEy
204    HErmann
203    Susan
202    Pat
201    MichaEl
200    JEnnifEr
199    Douglas
198    Donald
197    Kevin
196    Alana
...
*/
-- 151. 모든 사원들의 이름과 부서번호, 부서명을 조회한다. 근무중인 부서가 없는 경우도 조회한다.
SELECT E.FIRST_NAME 
	 , E.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME Z
  FROM EMPLOYEES E 
  LEFT OUTER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 152. 모든 사원들의 이름과 부서번호, 부서명, 근무중인 도시를 조회한다. 근무중인 부서가 없거나 근무중인 도시가 없는 경우도 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME 
	 , L.CITY
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT OUTER JOIN LOCATIONS L
  	ON D.LOCATION_ID = L.LOCATION_ID 
;
-- 153. 부서별로 근무중인 사원의 수를 조회한다. 근무중인 사원이 없는 부서는 0으로 조회한다.
SELECT DEPARTMENT_NAME
	 , NVL(EMP_CNT,0)
  FROM (SELECT D.DEPARTMENT_NAME 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 RIGHT OUTER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 GROUP BY D.DEPARTMENT_NAME)
 ORDER BY EMP_CNT DESC
;
-- 154. 도시별로 존재하는 부서의 수를 조회한다. 존재하는 부서가 없는 도시는 0으로 조회한다.
SELECT CITY
	 , DEPT_CNT
  FROM (SELECT L.CITY 
			 , COUNT(D.DEPARTMENT_ID ) AS DEPT_CNT
		  FROM DEPARTMENTS D
		 RIGHT OUTER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID 
		 GROUP BY L.CITY )
 ORDER BY DEPT_CNT DESC
;
-- 155. 도시별로 근무주인 사원의 수를 조회한다. 근무중인 사원이 없는 도시는 0으로 조회한다.
SELECT CITY
	 , EMP_CNT
  FROM (SELECT L.CITY 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		 RIGHT OUTER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID 
		 GROUP BY L.CITY)
 ORDER BY EMP_CNT DESC
;
SELECT L.CITY
	 , COUNT(D_E.EMPLOYEE_ID )
  FROM LOCATIONS L
  LEFT OUTER JOIN (SELECT D.LOCATION_ID 
  						, E.EMPLOYEE_ID 
   					 FROM DEPARTMENTS D
   					INNER JOIN EMPLOYEES E
   					   ON D.DEPARTMENT_ID = E.EMPLOYEE_ID) D_E
  	ON L.LOCATION_ID = D_E.LOCATION_ID
 GROUP BY L.CITY 
 ORDER BY L.CITY ASC
;
-- 156. 모든 사원의 정보와 직무 변경이력을 함께 조회한다. 직무변경이력이 없는 사원도 함께 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.EMAIL 
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.SALARY 
	 , E.JOB_ID 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID 
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOB_HISTORY JH 
  	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
;
-- 157. 모든 사원의 현재 수행중인 직무명, 현재 근무중인 부서명, 이전에 수행한 직무명, 이전에 근무한 부서명을 조회한다.
--     과거 직무와 이전 부서명이 없는 사원도 함께 조회한다.
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , P_J.JOB_TITLE 
	 , P_D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOBS J
  	ON E.JOB_ID = J.JOB_ID 
  LEFT OUTER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
  LEFT OUTER JOIN JOB_HISTORY JH
	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  LEFT OUTER JOIN JOBS P_J
  	ON JH.JOB_ID = P_J.JOB_ID 
  LEFT OUTER JOIN DEPARTMENTS P_D
 	ON JH.DEPARTMENT_ID = P_D.DEPARTMENT_ID 
 ORDER BY E.EMPLOYEE_ID ASC
;
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , JH.JOB_TITLE 
	 , JH.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
  	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
  LEFT OUTER JOIN (SELECT JH.EMPLOYEE_ID
  						, P_D.DEPARTMENT_NAME 
  						, P_J.JOB_TITLE 
					 FROM JOB_HISTORY JH
					INNER JOIN JOBS P_J
					   ON JH.JOB_ID = P_J.JOB_ID 
					INNER JOIN DEPARTMENTS P_D
					   ON JH.DEPARTMENT_ID = P_D.DEPARTMENT_ID) JH
	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 ORDER BY E.EMPLOYEE_ID ASC
;