-- 151. 모든 사원들의 이름과 부서번호, 부서명을 조회한다. 근무중인 부서가 없는 경우도 조회한다.
SELECT E.FIRST_NAME 
	 , E.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME Z
  FROM EMPLOYEES E 
  LEFT OUTER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 152. 모든 사원들의 이름과 부서번호, 부서명, 근무중인 도시를 조회한다. 근무중인 부서가 없거나 근무중인 도시가 없는 경우도 조회한다.
SELECT E.FIRST_NAME 
	 , E.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME 
	 , L.CITY
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT OUTER JOIN LOCATIONS L
  	ON D.LOCATION_ID = L.LOCATION_ID 
;
-- 153. 부서별로 근무중인 사원의 수를 조회한다. 근무중인 사원이 없는 부서는 0으로 조회한다.
SELECT DEPARTMENT_NAME
	 , EMP_CNT
  FROM (SELECT D.DEPARTMENT_NAME 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 RIGHT OUTER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 GROUP BY D.DEPARTMENT_NAME)
 ORDER BY EMP_CNT DESC
;
-- 154. 도시별로 존재하는 부서의 수를 조회한다. 존재하는 부서가 없는 도시는 0으로 조회한다.
SELECT CITY
	 , DEPT_CNT
  FROM (SELECT L.CITY 
			 , COUNT(D.DEPARTMENT_ID ) AS DEPT_CNT
		  FROM DEPARTMENTS D
		 RIGHT OUTER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID 
		 GROUP BY L.CITY )
 ORDER BY DEPT_CNT DESC
;
-- 155. 도시별로 근무주인 사원의 수를 조회한다. 근무중인 사원이 없는 도시는 0으로 조회한다.
SELECT CITY
	 , EMP_CNT
  FROM (SELECT L.CITY 
			 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		 RIGHT OUTER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID 
		 GROUP BY L.CITY)
 ORDER BY EMP_CNT DESC
;
-- 156. 모든 사원의 정보와 직무 변경이력을 함께 조회한다. 직무변경이력이 없는 사원도 함께 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.EMAIL 
	 , E.PHONE_NUMBER 
	 , E.HIRE_DATE 
	 , E.SALARY 
	 , E.JOB_ID 
	 , E.COMMISSION_PCT 
	 , E.MANAGER_ID 
	 , E.DEPARTMENT_ID 
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOB_HISTORY JH 
  	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
;
-- 157. 모든 사원의 현재 수행중인 직무명, 현재 근무중인 부서명, 이전에 수행한 직무명, 이전에 근무한 부서명을 조회한다.
--     과거 직무와 이전 부서명이 없는 사원도 함께 조회한다.
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , P_J.JOB_TITLE 
	 , P_D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOBS J
  	ON E.JOB_ID = J.JOB_ID 
  LEFT OUTER JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
  LEFT OUTER JOIN JOB_HISTORY JH
	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  LEFT OUTER JOIN JOBS P_J
  	ON JH.JOB_ID = P_J.JOB_ID 
  LEFT OUTER JOIN DEPARTMENTS P_D
 	ON JH.DEPARTMENT_ID = P_D.DEPARTMENT_ID 
 ORDER BY E.EMPLOYEE_ID ASC
;
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , JH.EMPLOYEE_ID 
  FROM JOB_HISTORY JH 
  LEFT OUTER JOIN JOBS J
  	ON JH.JOB_ID = J.JOB_ID 
  LEFT OUTER JOIN DEPARTMENTS D
  	ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
