--1. 전체 사원 중 3번째로 빠르게 입사한 사원의 이름과 입사일을 연-월-일 포멧으로 조회하시오.
SELECT FIRST_NAME
	 , TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
  FROM (SELECT FIRST_NAME
			 , HIRE_DATE
			 , ROW_NUMBER() OVER(ORDER BY HIRE_DATE ASC)
		  FROM EMPLOYEES)
;

--2. 전체 사원 중 11번째로 늦게 입사한 사원의 이름과 입사일을 연-월-일 포멧으로 조회하시오.
SELECT FIRST_NAME
	 , TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
  FROM (SELECT FIRST_NAME
			 , HIRE_DATE
			 , ROW_NUMBER() OVER(ORDER BY HIRE_DATE DESC) AS DATE_RNK
		  FROM EMPLOYEES)
 WHERE DATE_RNK = 11
;
--3. 2006년에 입사한 사원 중 2번째로 빠르게 입사한 사원의 이름과 입사일을 연-월-일 포멧으로 조회하시오.

SELECT FIRST_NAME
	 , TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
  FROM(SELECT FIRST_NAME
  			, HIRE_DATE
			, ROW_NUMBER() OVER(ORDER BY HIRE_DATE ASC) AS HIRE_RNK
	  	 FROM EMPLOYEES
	  	WHERE HIRE_DATE < TO_DATE('20070101', 'YYYY-MM-DD')
	  	  AND HIRE_DATE >= TO_DATE('20060101', 'YYYY-MM-DD'))
 WHERE HIRE_RNK = 2	  	  
;	  	 
--4. 3번째로 많은 사원이 수행중인 직무의 이름과 사원 수를 조회하시오.
SELECT J.JOB_TITLE
	 , COUNT(E.EMPLOYEE_ID)
  FROM JOBS J
 INNER JOIN EMPLOYEES E
 	ON J.JOB_ID = E.JOB_ID 
 WHERE J.JOB_ID IN (SELECT JOB_ID
					  FROM (SELECT JOB_ID
								 , ROW_NUMBER() OVER(ORDER BY EMP_CNT DESC) AS EMP_RANK
							  FROM (SELECT JOB_ID
										 , COUNT(EMPLOYEE_ID) AS EMP_CNT
									  FROM EMPLOYEES
									 GROUP BY JOB_ID))
					 WHERE EMP_RANK = 3)
 GROUP BY JOB_TITLE
;