SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
  FROM EMPLOYEES
;

--DEPARTMENTS 테이블에서
-- DEPARTMEMT_ID M MANAGER_ID 만 조회해 본다

SELECT DEPARTMENT_ID
	 , MANAGER_ID
  FROM DEPARTMENTS
;

--COUNTRIES 테이블에서 
--COUNTRY_ID, COUNTRY_NAME, REGION_ID를 조회해본다.
SELECT COUNTRY_ID
	 , COUNTRY_NAME
	 , REGION_ID
  FROM COUNTRIES
;

SELECT *
  FROM COUNTRIES
;

-- 1. 사원의 이름과 성 그리고 급여를 조회한다.
SELECT FIRST_NAME
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
;
-- 2. 부서의 부서장 번호화 부서가 존재하는 지역의 번호를 조회한다.
SELECT MANAGER_ID
	 , LOCATION_ID
  FROM DEPARTMENTS
;  
 
-- 3. 국가의 아이디 이름 국가가 존재하는 대륙의 번호를 조회한다.
SELECT COUNTRY_ID
	 , COUNTRY_NAME
	 , REGION_ID
  FROM COUNTRIES
;

-- 4. 직무의 이름과 최대급여를 조회한다.
SELECT JOB_TITLE
	 , MAX_SALARY
  FROM JOBS
;

-- 5. 지역의 도시명과 주소, 우편 번호를 조회한다.
SELECT CITY
	 , STREET_ADDRESS
	 , POSTAL_CODE
  FROM LOCATIONS
;

-- 6. 사원의 상사사원번호와 입사일 그리고 연락처를 조회한다.
SELECT MANAGER_ID
	 , HIRE_DATE
	 , PHONE_NUMBER
  FROM EMPLOYEES
;

-- 7. 직무가 변경된 사원의 이전 직무아이디, 이전 직무를 수행한 부서의 아이디, 이전 직무를 시작한 날짜를 조회한다.
SELECT JOB_ID
	 , DEPARTMENT_ID
	 , START_DATE
  FROM JOB_HISTORY
;
-- 8. 대륙의 아이디와 이름을 조회한다.
SELECT REGION_ID
	 , REGION_NAME
  FROM REGIONS
;
-- 9. 사원의 직무 아이디와 부서번호만 조회한다.
SELECT JOB_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
; 
-- 10. 사원의 이름, 성, 급여, 입사일, 부서의 이름, 부서장의 이름, 지역의 도시명, 국가명, 대륙의 이름을 조회한다.

-- 모든 사원들의 이름, 성, 급여를 중복 없이 조회한다.
SELECT DISTINCT FIRST_NAME
	 , LAST_NAME
	 , SALARY 
  FROM EMPLOYEES
;
-- 모든 사원들의 급여와 커미션을 중복없이 조회한다.
SELECT DISTINCT SALARY
	 , COMMISSION_PCT 
  FROM EMPLOYEES
;
-- 현재 날짜와 시간을 "연-월-일 시:분:초 형태로 보여준다."
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MM:SS') 
  FROM DUAL
;

-- 현재 날짜와 시간을 보여준다.
SELECT SYSDATE 
  FROM DUAL
;
-- 현재 날짜에서 하루를 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 1
  FROM DUAL
;
-- 현재 날짜에서 이틀을 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 2
  FROM DUAL
;
-- 현재 날짜에서 한달을 더한 날짜와 시간을 보여준다.
SELECT ADD_MONTHS(SYSDATE, 1)
  FROM DUAL
;
-- 현재 날짜에서 한달을 뺀 날짜와 시간을 보여준다.
SELECT ADD_MONTHS(SYSDATE, -1)
  FROM DUAL
;
-- 현재 날짜에서 이틀을 뺀 날짜와 시간을 보여준다.
SELECT SYSDATE - 2
  FROM DUAL
;
-- 현재 날짜에서 하루를 뺀 날짜와 시간을 보여준다.
SELECT SYSDATE - 1
  FROM DUAL
;
-- 현재 날짜에서 1시간을 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 1/24
  FROM DUAL
;
-- 현재 날짜에서 5시간을 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 5/24
  FROM DUAL
;
-- 현재 날짜에서 10시간을 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 10/24
  FROM DUAL
;
-- 현재 날짜에서 1분을 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 1/24/60
  FROM DUAL
;
-- 현재 날짜에서 13분을 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 13/24/60
  FROM DUAL
;
-- 현재 날짜에서 49초를 더한 날짜와 시간을 보여준다.
SELECT SYSDATE + 49/24/60/60
  FROM DUAL
;

-- 부서의 이름, 부서장의 번호, 지역의 번호를 조회한다.
-- 이 때, 부서장의 번호로 오름차순 정렬한다.
SELECT DEPARTMENT_NAME
	 , MANAGER_ID 
	 , LOCATION_ID 
  FROM DEPARTMENTS 
 ORDER BY MANAGER_ID ASC
;

-- 부서의 지역번호를 중복없이 조회한다.
-- 이 때, 지역번호로 내림차순 정렬한다.
SELECT DISTINCT LOCATION_ID
  FROM DEPARTMENTS
 ORDER BY LOCATION_ID  DESC
;

-- 사원의 급여와, 커미션 비율, 이름, 성을 조회한다.
-- 이 때, 급여로 오름차순 정렬하고 같은 급여가 있을 경우 커미션 비율로 내림차순 정렬한다.
SELECT SALARY 
	 , COMMISSION_PCT 
	 , FIRST_NAME 
	 , LAST_NAME 
  FROM EMPLOYEES
 ORDER BY SALARY ASC
 	 , COMMISSION_PCT DESC
;

-- 사원 번호가 108번인 사원의 사원번호, 이름, 성을 조회한다.
SELECT EMPLOYEE_ID 
	 , FIRST_NAME 
	 , LAST_NAME 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = '108'
;

-- 이름이 'Steven'인 사원의 이름과 성, 급여, 근무부서번호를 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME 
	 , SALARY 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME = 'Steven'
;

-- 근무부서 번호가 50인 사원의 이름과, 성, 상사사원번호, 직무 아이디를 조회한다.
-- 이 때, 상사사원번호로 내림차순 정렬한다.
SELECT FIRST_NAME
	 , LAST_NAME 
	 , MANAGER_ID
	 , JOB_ID 
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 50
;

-- 도시의 이름이 'Seattle'인 지역의 지역번호, 주소, 주, 국가아이디를 조회한다.
SELECT LOCATION_ID 
	 , STREET_ADDRESS 
	 , STATE_PROVINCE 
	 , COUNTRY_ID 
  FROM LOCATIONS
  WHERE CITY = 'Seattle'
;

-- 101번 사원의 직무변경이력 중 직무 시작일, 직무 종료일, 직무 아이디, 근무 부서 아이디를 조회한다.
-- 이 때, 직무 시작일로 오름차순 정렬한다.
SELECT START_DATE 
	 , END_DATE 
	 , JOB_ID 
	 , DEPARTMENT_ID 
  FROM JOB_HISTORY 
  WHERE EMPLOYEE_ID = 101
 ORDER BY START_DATE ASC
;

-- 급여가 10000 이상인 사원의 사원번호, 직무아이디, 급여, 근무부서 아이디를 조회한다.
-- 직무아이디 오름차순, 근무부서번호 오름차순, 급여 내림차순으로 정렬한다.
SELECT EMPLOYEE_ID 
	 , JOB_ID
	 , SALARY
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
  WHERE SALARY >= 10000
 ORDER BY EMPLOYEE_ID ASC 
 	 , DEPARTMENT_ID ASC
 	 , SALARY DESC
;

-- 커미션 비율이 0.2보다 작은 사원의 급여, 커미션 비율을 조회한다.
-- 급여 오름차순 정렬한다.
SELECT SALARY 
	 , COMMISSION_PCT 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT < 0.2
 ORDER BY SALARY ASC
;
-- 근무부서 번호가 50이 아닌 사원들의 부서번호, 직무 아이디를 조회한다.
SELECT DEPARTMENT_ID
	 , JOB_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID != 50
;

-- 급여가 8000 이상이면서 커미션을 받는 사원의 급여, 커미션비율을 조회한다.
SELECT SALARY
	 , COMMISSION_PCT 
  FROM EMPLOYEES
 WHERE SALARY >= 8000
   AND COMMISSION_PCT IS NOT NULL
;
-- 급여가 10000 이상이거나 커미션을 받는 사원의 급여, 커미션 비율을 조회한다.
SELECT SALARY
	 , COMMISSION_PCT 
  FROM EMPLOYEES
 WHERE SALARY >= 10000 
 	OR COMMISSION_PCT IS NOT NULL
;
-- 10번 20번 50번 부서번호에서 근무하는 모든 사원들의 근무부서 번호, 직무 아이디를 조회한다.
SELECT DEPARTMENT_ID
	 , JOB_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (10, 20 ,50)
;
-- 급여가 5000이상 10000미만이거나 직무 아이디가 IT_PROG 인 사원의 급여와 직무 아이디를 조회한다.
SELECT SALARY 
	 , JOB_ID  
  FROM EMPLOYEES
 WHERE (SALARY >= 5000 AND SALARY < 10000) OR JOB_ID = 'IT_PROG'
;
-- 직무아이디가 IT_PROG, FI_ACCOUNT가 아닌 사원들의 직무 아이디를 중복없이 조회한다.
SELECT DISTINCT JOB_ID
  FROM EMPLOYEES
 WHERE JOB_ID NOT IN ('IT_PROG', 'FI_ACCOUNT')
;
SELECT DISTINCT JOB_ID
  FROM EMPLOYEES
 WHERE JOB_ID != 'IT_PROG'
   AND JOB_ID != 'FI_ACCOUNT'
;

-- 급여가 2000~5000 사이 이거나 직무 아이디가 ST_MAN, SA_REP가 아닌 사원들의 급여와 직무 아이디를 조회한다.
SELECT SALARY 
	 , JOB_ID 
  FROM EMPLOYEES
 WHERE (SALARY BETWEEN 2000 AND 5000) 
 	OR (JOB_ID NOT IN ('ST_MAN', 'SA_REP'))
;
SELECT SALARY 
	 , JOB_ID 
  FROM EMPLOYEES
 WHERE SALARY >= 2000 
   AND SALARY <= 5000
    OR JOB_ID NOT IN ('ST_MAN', 'SA_REP')
;

-- 상사 사원번호가 101번 이거나 103번인 사원 중 급여가 5000 이상인 사원의 상사 사원번호와 급여를 조회한다.
SELECT MANAGER_ID 
	 , SALARY 
  FROM EMPLOYEES
 WHERE (MANAGER_ID = 101 OR MANAGER_ID = 103)
   AND SALARY >= 5000
;
SELECT MANAGER_ID 
	 , SALARY 
  FROM EMPLOYEES
 WHERE MANAGER_ID IN (101,103) 
   AND SALARY >= 5000
;

SELECT FIRST_NAME 
	 , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID NOT IN(10,20,30,40)
;

SELECT ADD_MONTHS(SYSDATE, -240)
  FROM DUAL
;  

-- 이름이 'a'로 끝나는 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%a'
;
-- 성이 'A'로 시작하는 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'A%'
;
-- 이름과 성에 'e'가 있는(포함되어있는) 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%e%'
   AND LAST_NAME LIKE '%e%'
;
-- 이름 또는 성에 'g'가 있는(포함되어있는) 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%g%'
   AND LAST_NAME LIKE '%g%'
;
-- 이름이 5자리인 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '_____'
;
-- 이름이 4자리 이상인 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%____%'
;
-- 성이 4자리 이상이며 다섯번째 자리의 글자가 'e'인 사원의 이름과 성을 조회한다.
SELECT FIRST_NAME 
	 , LAST_NAME
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE '____e%'
;
-- 도시명이 'S'로 시작하는 도시의 이름을 조회한다.
SELECT CITY
  FROM LOCATIONS
 WHERE CITY LIKE 'S%'
;
-- 부서의 이름에 'r'이 있는(포함되어있는) 부서의 이름을 조회한다.
SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME LIKE '%r%'
;

-- 전체 사원의 수를 조회한다.
SELECT COUNT(*)
  FROM EMPLOYEES
;
SELECT COUNT(1)
  FROM EMPLOYEES
;
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
;
-- 70번 부서에서 근무 중인 사원의 수를 조회한다.
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 70
;

-- 전체 사원들의 급여 총 합을 조회한다.
SELECT SUM(SALARY)
  FROM EMPLOYEES
;
-- 전체 사원 중 최저 급여를 조회한다.
SELECT MIN(SALARY)
  FROM EMPLOYEES
;
-- 전체 사원 중 최고 급여를 조회한다.
SELECT MAX(SALARY)
  FROM EMPLOYEES
;
-- 전체 사원의 평균 급여를 조회한다.
SELECT AVG(SALARY)
  FROM EMPLOYEES
;
-- 전체 사원 중 가장 일찍 입사한 날짜를 조회한다.
SELECT MIN(HIRE_DATE)
  FROM EMPLOYEES
;
-- 전체 사원 중 가장 늦게 입사한 날짜를 조회한다.
SELECT MAX(HIRE_DATE)
  FROM EMPLOYEES
;
-- 50번 부서에서 근무하는 사원들의 급여 총합을 조회한다.
SELECT SUM(SALARY)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 50
;
-- 60번 부서에서 근무하는 사원들의 평균 급여를 조회한다.
SELECT AVG(SALARY)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 60
;
-- 80번 부서에서 근무하는 사원들의 최고 급여를 조회한다.
SELECT MAX(SALARY)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 80
;
-- 90번 부서에서 근무하는 사원들의 최저 급여를 조회한다.
SELECT MIN(SALARY)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 90
;
-- 100번 부서에서 근무하는 사원들의 최고 급여, 최저 급여,
-- 가장 일찍 입사한 날짜, 가장 늦게 입사한 날짜, 평균 급여, 급여 총합을 조회한다.
SELECT MAX(SALARY)
	 , MIN(SALARY)
	 ,TO_CHAR(MIN(HIRE_DATE) , 'YYYY-MM-DD') AS EARLIEST_HIRED
	 ,TO_CHAR(MAX(HIRE_DATE) , 'YYYY-MM-DD') AS LATEST_HIRED
	 , AVG(SALARY)
	 , SUM(SALARY)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 100
;
-- 전체 사원들의 최고 급여와 최저 급여의 차를 조회한다.
SELECT MAX(SALARY) - MIN(SALARY)
  FROM EMPLOYEES
 ;

-- 같은 급여별 받는 사원들은 몇명인지 급여별 사원의 수를 조회한다.
SELECT SALARY  
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY SALARY
 ORDER BY SALARY ASC
;
-- 직무 아이디별 사원의 수, 급여의 총합, 평균 급여, 최고 급여, 최소 급여, 
--    가장 빠른 입사일, 가장 늦은 입사일을 조회한다.
SELECT COUNT(EMPLOYEE_ID)
	 , SUM(SALARY)
	 , AVG(SALARY)
	 , MAX(SALARY)
	 , MIN(SALARY)
	 , MIN(HIRE_DATE)
	 , MAX(HIRE_DATE)
  FROM EMPLOYEES
 GROUP BY JOB_ID 

-- 부서의 지역번호 별 부서의 개수를 조회한다.
SELECT COUNT(DEPARTMENT_ID )
  FROM DEPARTMENTS
 GROUP BY LOCATION_ID 
;
-- 지역의 국가아이디 별 지역의 개수를 조회한다.
SELECT COUNT(LOCATION_ID )
  FROM LOCATIONS
 GROUP BY COUNTRY_ID 
;
-- 부서번호 별 사원의 수, 급여의 총합을 조회한다.
-- 이 때, 사원의 수가 2이상인 것과 급여의 총합이 20000 이상인것만 조회한다.
SELECT COUNT(EMPLOYEE_ID )
	 , SUM(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) > 1
   AND SUM(SALARY) >= 20000 
;

-- 같은 급여를 받는 사원들은 몇 명인지 급여별 사원의 수를 조회한다.
-- 이 때, 사원의 수가 1인 것은 제외한다.
SELECT SALARY  
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY SALARY
HAVING COUNT(EMPLOYEE_ID) > 1
 ORDER BY SALARY ASC
;

-- 평균 급여보다 많은 급여를 받는 사원의 이름, 성, 급여를 조회한다.
-- 1.특정할 수 없는 데이터가 무엇인가? ==> 평균 급여 = 6461.831775700934579439252336448598130841
SELECT AVG(SALARY)
  FROM EMPLOYEES
;
-- 2.특정할 수 없는 평균 급여를 무엇과 비교를 해야하는가?
-- 사원들의 급여와 비교한다.
SELECT FIRST_NAME 
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY > 6461.831775700934579439252336448598130841
;
-- 두 쿼리를 하나로 합친다.
SELECT FIRST_NAME 
	 , LAST_NAME
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
  				   FROM EMPLOYEES)	
;

-- IT 부서에서 근무중인 사원들의 부서 번호와 이름을 조회한다.
-- 1. 특정할 수 없는 것 == IT 부서의 부서 번호
SELECT DEPARTMENT_ID 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_NAME = 'IT'
;
-- 2. 무엇과 비교를 해야 하는가?
SELECT DEPARTMENT_ID 
	 , FIRST_NAME 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 60
;

SELECT DEPARTMENT_ID 
	 , FIRST_NAME 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
  						  FROM DEPARTMENTS
 						 WHERE DEPARTMENT_NAME = 'IT')	
;

-- "Marketing Representative" 이름의 직무를 수행 중인 사원의 직무 아이디, 급여를 조회한다.
-- 1. 특정할 수 없는것? = > "Marketing Representative" 직무의 아이디
SELECT JOB_ID
  FROM JOBS
 WHERE JOB_TITLE = 'Marketing Representative'
;

-- 2. 무엇과 비교해야하는가? => 사원의 직무 아이디
SELECT JOB_ID 
	 , SALARY 
  FROM EMPLOYEES
 WHERE JOB_ID = 'Marketing Representative'
;
-- 3. 하나로 합친다.
 SELECT JOB_ID 
	  , SALARY 
  FROM EMPLOYEES
 WHERE JOB_ID = (SELECT JOB_ID
  				   FROM JOBS
 				  WHERE JOB_TITLE = 'Marketing Representative')
;


-- ERD

-- UNION 규칙
-- 집합간의 컬럼타입이 일치해야 한다.
SELECT 1 AS NUM
	 , 'A' AS STR
  FROM DUAL
 UNION
SELECT 2
	 , 'B'
  FROM DUAL
;

SELECT 1 AS NUM
  FROM DUAL
 UNION
SELECT 2
  FROM DUAL
 UNION ALL
SELECT 2
  FROM DUAL
;

SELECT 1 AS NUM
  FROM DUAL
 UNION ALL
SELECT 2
  FROM DUAL
 UNION ALL
SELECT NUM2
  FROM (SELECT -1 AS NUM2
  		  FROM DUAL
  		 UNION ALL
  		SELECT 0 AS NUM2
  		  FROM DUAL
  		 UNION ALL
  		SELECT -7 AS NUM2
  		  FROM DUAL
  		ORDER BY NUM2 ASC)
;


-- MOD -> 나머지 구하는 함수
SELECT MOD(10,3)
	 , MOD(10,2)
  FROM DUAL
;

-- CASE WHEN ELSE END
-- 비교 연산 (IF ~ ELSE IF ELSE)
WITH TMP AS (
SELECT 'Y' AS FLAG
  FROM DUAL
 UNION
SELECT 'N'
  FROM DUAL
 UNION
SELECT 'R'
  FROM DUAL
 UNION
SELECT NULL
  FROM DUAL
)
-- TMP테이블의 FLAG 컬럼의 값이 'Y' 라면 "On" 으로 조회하고, 'R'이라면 "Ready'로 조회하고, 아니라면 "Off"로 조회한다.
-- NULL 이라면 Error를 조회한다.
SELECT FLAG 
	 , CASE 
	 		WHEN FLAG = 'Y' THEN
	 			'On'
	 		WHEN FLAG = 'R' THEN
	 			'Ready'
	 		WHEN FLAG IS NULL THEN
	 			'Error'
	 		ELSE
	 			'Off'
	 	END AS ON_OFF 
  FROM TMP
;

WITH NUMBERS AS(
	SELECT 10 AS NUM
	  FROM DUAL
	 UNION
	SELECT 20 
	  FROM DUAL
	 UNION
	SELECT 30
	  FROM DUAL
)
-- NUM값이 30이상이면 "3", 20이상이면 "2", 10이상이면 "1" 아니면 "0"으로 조회한다.
SELECT NUM 
	 , CASE
	 		WHEN NUM >= 30 THEN '3'
	 		WHEN NUM >= 20 THEN '2'
	 		WHEN NUM >= 10 THEN '1'
	 		ELSE '0'
	 END AS NUM_BOOL
  FROM NUMBERS
;

-- 1, 사원의 사원번호, 부서번호, 근무현황을 조회한다.
-- 근무현황: 근무하는 부서가 있을 경우 "근무 중", 아닐 경우 "발령 대기"
SELECT EMPLOYEE_ID
	 , DEPARTMENT_ID
	 , CASE
	 		WHEN DEPARTMENT_ID IS NOT NULL THEN '근무 중'
	 		ELSE '발령 대기'
	 END AS "근무 현황"
  FROM EMPLOYEES
;
	 
-- 2. 사원의 사원 번호, 입사일, 입사순서를 조회한다.
-- 입사 순서: 가장 빨리 입사한 사원은 "원년 사원", 가장 늦게 입사한 사원은 "신규 사원", 아닐 경우 "사원"
SELECT EMPLOYEE_ID
	 , HIRE_DATE
	 , CASE
	 		 WHEN HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEES ) THEN '원년 사원'
	 		 WHEN HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM EMPLOYEES ) THEN '신규 사원'
	 		 ELSE '사원'
	 END AS "입사 순서"
  FROM EMPLOYEES
;
-- 임시 테이블
WITH DATES AS (
	SELECT MAX(HIRE_DATE) AS MAX_HIRE_DATE
		 , MIN(HIRE_DATE) AS MIN_HIRE_DATE
	  FROM EMPLOYEES
)
SELECT EMPLOYEE_ID
	 , HIRE_DATE
	 , CASE HIRE_DATE
	 		WHEN MAX_HIRE_DATE THEN '신규 사원'
	 		WHEN MIN_HIRE_DATE THEN '원년 사원'
	 		ELSE '사원'
	   END AS "입사 순서"
  FROM EMPLOYEES ,DATES
;
-- CROSS JOIN (데이터를 조건 상관 없이 모든 ROW에 다 같다 붙이는 조인)
SELECT EMPLOYEE_ID
	 , HIRE_DATE
	 , CASE HIRE_DATE
	 	 	WHEN DATES.MAX_HIRE_DATE THEN '신규 사원'
	 	 	WHEN DATES.MIN_HIRE_DATE THEN '원년 사원'
	 	 	ELSE '사원'
	   END AS "입사 순서"
  FROM EMPLOYEES
 CROSS JOIN (SELECT MAX(HIRE_DATE) AS MAX_HIRE_DATE
 				  , MIN(HIRE_DATE) AS MIN_HIRE_DATE
 			   FROM EMPLOYEES) DATES
;
 		
	 
-- LPAD, RPAD 오라클 전용
-- 실제로는 LPAD의 사용빈도가 더 높음
SELECT 'A' AS LETTER
	 , 10 AS NUM
	 , LPAD('A', 10, '1')
	 , LPAD(10, 10, '-')
	 , RPAD('A', 10, '1')
	 , RPAD(10, 10, '-')
	 , LPAD('ABCDEFGHIJKLMNOP', 10, '!')
	 , RPAD('ABCDEFGHIJKLMNOP', 10, '!')
  FROM DUAL
;

-- 단위 숫자 버림 TRUNC()
SELECT EMPLOYEE_ID
	 , SALARY
	 , SALARY /1000
	 , TRUNC(SALARY/1000)
	 , TRUNC(SALARY /1000) *1000
  FROM EMPLOYEES
;

-- OUTER JOIN
-- 모든 사원들의 이름과 부서의 이름을 조회한다.
-- 근무중인 부서가 없다면 NULL로 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
  LEFT OUTER JOIN DEPARTMENTS D 
  	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;  	

-- 모든 부서 이름별 근무중인 사원의 수를 조회한다.
-- 근무중인 사원이 없다면 사원의 수를 0으로 한다. 
SELECT D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID)
  FROM DEPARTMENTS D
  LEFT OUTER JOIN EMPLOYEES E
  	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME
; 

SELECT D.DEPARTMENT_NAME
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 RIGHT OUTER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
;
-- 모든 도시의 이름과 부서의 이름을 조회한다.
-- 존재하는 부서가 없다면 NULL로 조회한다.  
SELECT L.CITY
	 , D.DEPARTMENT_NAME 
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
  	ON L.LOCATION_ID = D.LOCATION_ID 
;
-- 모든 국가의 이름과 도시의 이름을 조회한다.
-- 존재하는 도시가 없다면 NULL로 조회한다.
SELECT C.COUNTRY_NAME
	 , L.CITY 
  FROM COUNTRIES C
  LEFT OUTER JOIN LOCATIONS L
  	ON C.COUNTRY_ID = L.COUNTRY_ID 
;
-- 모든 국가별 사원들의 평균 급여를 조회한다.
-- 근무하는 사원이 없다면 0으로 조회한다.
SELECT C.COUNTRY_NAME
	 ,NVL(L.SAL_AVG,0)
  FROM COUNTRIES C
  LEFT OUTER JOIN (SELECT L.COUNTRY_ID 
						, AVG(E.SALARY) AS SAL_AVG
					 FROM EMPLOYEES E
					INNER JOIN DEPARTMENTS D
					   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
					INNER JOIN LOCATIONS L
					   ON D.LOCATION_ID = L.LOCATION_ID
					GROUP BY L.COUNTRY_ID ) L
	ON C.COUNTRY_ID = L.COUNTRY_ID 
;  
SELECT C.COUNTRY_NAME
	 , NVL(AVG(E.SALARY),0) AS SAL_AVG
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 RIGHT OUTER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 GROUP BY C.COUNTRY_NAME
;

-- 모든 도시의 이름, 도시에 존재하는 부서명, 부서에서 근무중인 사원명, 사원이 수행하는 직무명을 조회한다.
-- 없을 경우 NULL로 조회한다.
SELECT CITY
	 , D.DEPARTMENT_NAME 
	 , D.FIRST_NAME 
	 , D.JOB_TITLE 
  FROM LOCATIONS L
  LEFT OUTER JOIN (SELECT E.FIRST_NAME 
						 , J.JOB_TITLE 
						 , D.DEPARTMENT_NAME
						 , D.LOCATION_ID 
					  FROM EMPLOYEES E
					 INNER JOIN JOBS J
					 	ON E.JOB_ID = J.JOB_ID 
					 RIGHT OUTER JOIN DEPARTMENTS D
					 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID) D
	ON L.LOCATION_ID = D.LOCATION_ID
;
SELECT L.CITY 
	 , E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME
	 , D.LOCATION_ID 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
	ON E.JOB_ID = J.JOB_ID 
 RIGHT OUTER JOIN DEPARTMENTS D
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 RIGHT OUTER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
;
-- Scala Query
-- 사원의 이름과 직무명을 조회한다. 이때, 직무 테이블은 INNER JOIN하지 않는다.
SELECT E.FIRST_NAME
	 , E.JOB_ID 
	 , (SELECT J.JOB_TITLE
	 	  FROM JOBS J 
	 	 WHERE J.JOB_ID = E.JOB_ID ) AS TITLE
  FROM EMPLOYEES E
;
-- 사원의 이름과 부서명을 조회한다. 이때, 부서 테이블은 INNER JOIN하지 않는다.
SELECT E.FIRST_NAME
	 , (SELECT D.DEPARTMENT_NAME 
	 	  FROM DEPARTMENTS D 
	 	 WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID ) AS DEPT_NAME
  FROM EMPLOYEES E
;
-- 사원의 이름과 상사의 이름을 조회한다. 이때, 사원(상사) 테이블은 INNER JOIN하지 않는다.
SELECT E.FIRST_NAME
	 , (SELECT M.FIRST_NAME 
	 	  FROM EMPLOYEES M 
	 	 WHERE M.EMPLOYEE_ID  = E.MANAGER_ID ) AS MANAGER_NAME
  FROM EMPLOYEES E
;

-- 사원의 이름과 급여, 전체 사원들의 평균 급여를 조회한다.
SELECT FIRST_NAME
	 , SALARY
	 , (SELECT AVG(SALARY) FROM EMPLOYEES) AS SALARY_AVG
  FROM EMPLOYEES
;

-- Sub query join
-- 사원이 근무중인 부서에서 최저 급여을 받는 사원의 이름, 급여, 부서번호를 조회한다.
SELECT FIRST_NAME
	 , SALARY
	 , DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE SALARY = (SELECT MIN(SALARY)
 				   FROM EMPLOYEES E2
 				  WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID )
;
-- 사원이 수행중인 직무에서 최저 급여를 받는 사원의 이름, 급여, 직무아이디를 조회한다.
SELECT E.FIRST_NAME
	 , E.SALARY
	 , E.JOB_ID 
  FROM EMPLOYEES E
 WHERE SALARY = (SELECT MIN(SALARY)
 				   FROM EMPLOYEES E2
 				  WHERE E2.JOB_ID  = E.JOB_ID )
; 				  
-- 사원이 근무중인 부서에서 부서장으로 근무하는 사원의 이름, 급여, 부서번호를 조회한다.
SELECT E.FIRST_NAME
	 , E.SALARY
	 , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.EMPLOYEE_ID = (SELECT MANAGER_ID
 							FROM DEPARTMENTS D
 						 WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID )
; 							
 				  
-- Oracle Concat
-- 사원의 이름과 성을 한 컬럼으로 조회한다.
SELECT FIRST_NAME
	 , LAST_NAME
  FROM EMPLOYEES
;
SELECT FIRST_NAME || ' ' ||LAST_NAME AS NAME
  FROM EMPLOYEES
;

-- 사원의 이름, 사원이 근무중인 부서의 이름, 부서장 사원 번호를 한 컬럼으로 조회한다.
SELECT E.FIRST_NAME || ' ' || D.DEPARTMENT_NAME || ' ' || D.MANAGER_ID 
 FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 사원의 이름, 사원이 근무중인 부서의 이름과 부서장 사원의 이름을 한 컬럼으로 조회한다.
SELECT EMPL.FIRST_NAME || ' ' || D.DEPARTMENT_NAME || ' ' || D.FIRST_NAME AS MANAGER_NAME
  FROM EMPLOYEES EMPL
 INNER JOIN (SELECT D.DEPARTMENT_ID 
				  , D.DEPARTMENT_NAME
				  , E.FIRST_NAME
				  , D.MANAGER_ID 
			   FROM EMPLOYEES E
			  INNER JOIN DEPARTMENTS D
			 	 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
			  WHERE D.MANAGER_ID = E.EMPLOYEE_ID ) D
	ON EMPL.DEPARTMENT_ID = D.DEPARTMENT_ID 
;

SELECT E.FIRST_NAME || ' ' || D.DEPARTMENT_NAME || ' ' || MAN.FIRST_NAME AS MANAGER_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN EMPLOYEES MAN
 	ON D.MANAGER_ID = MAN.EMPLOYEE_ID 
;


-- 사원의 이름, 사원이 근무중인 부서의 이름과 부서장 사원의 이름을 한 컬럼으로 조회한다.(Scala Query) 
SELECT FIRST_NAME || ' ' 
	|| (SELECT D.DEPARTMENT_NAME FROM DEPARTMENTS D WHERE E.DEPARTMENT_ID  = D.DEPARTMENT_ID ) || ' ' 
	|| (SELECT M.FIRST_NAME  
		  FROM DEPARTMENTS D 
		 INNER JOIN EMPLOYEES M 
		 	ON D.MANAGER_ID = M.EMPLOYEE_ID  
		 WHERE D.DEPARTMENT_ID  = E.DEPARTMENT_ID) AS RESULT
  FROM EMPLOYEES E
;
-- ROW 순위 구하기

-- [DENSE_]RANK() OVER(), ROW_NUMBER() OVER() 없이 조회.
-- 사원 중 작은 급여를 받는 10명을 조회한다.
SELECT FIRST_NAME
	 , SALARY
  FROM (SELECT FIRST_NAME
			 , SALARY
		  FROM EMPLOYEES
		 ORDER BY SALARY ASC)
 WHERE ROWNUM <= 10
;		
-- 사원 중 많은 급여를 받는 10명을 조회한다.
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , SALARY
  FROM (SELECT EMPLOYEE_ID
 			 , FIRST_NAME
			 , SALARY
		  FROM EMPLOYEES
		 ORDER BY SALARY DESC)
 WHERE ROWNUM <= 10
;
-- 많은 급여를 받는 중 5 ~ 9 번째 사원을 조회한다.   
SELECT FIRST_NAME
	 , SALARY
  FROM (SELECT FIRST_NAME
			 , SALARY
			 , ROWNUM AS RNUM
		  FROM (SELECT EMPLOYEE_ID
		 			 , FIRST_NAME
					 , SALARY
				  FROM EMPLOYEES
				 ORDER BY SALARY DESC)
		 WHERE ROWNUM < 10)
 WHERE RNUM >= 5
;

-- 부서 정보(정렬 없음) 중 6번째 부터 12번째 까지의 부서 이름을 조회한다.
SELECT DEPARTMENT_NAME
	 , LOCATION_ID 
	 , MANAGER_ID 
  FROM (SELECT DEPARTMENT_ID
			 , DEPARTMENT_NAME 
			 , LOCATION_ID 
			 , MANAGER_ID
			 , ROWNUM AS RNUM
		  FROM DEPARTMENTS )
 WHERE RNUM >= 6
   AND RNUM <= 12 
;

-- 부서장이 있는 부서를 부서 명으로 오름차순 정렬한 결과에서 2번째부터 7번째까지 부서명만 조회한다.
SELECT DEPARTMENT_NAME
  FROM (SELECT DEPARTMENT_NAME
			 , RNUM
		  FROM (SELECT DEPARTMENT_ID 
			 , DEPARTMENT_NAME 
			 , ROWNUM AS RNUM
		  FROM (SELECT DEPARTMENT_ID 
					 , DEPARTMENT_NAME 
				  FROM DEPARTMENTS
				 WHERE MANAGER_ID IS NOT NULL
				 ORDER BY DEPARTMENT_NAME))
		 WHERE RNUM <= 7)
 WHERE RNUM >= 2		 
;

-- 커미션을 포함한 급여순으로 사원들을 내림차순 정렬하고 그 중 7번째~ 16번째 까지의 사원 이름과 급여를 조회한다.
SELECT FIRST_NAME
			 , COMM_SAL
			 , RNUM
		  FROM (SELECT FIRST_NAME
					 , COMM_SAL
					 , ROWNUM AS RNUM
				  FROM (SELECT FIRST_NAME
							 , SALARY
							 , SALARY+ (SALARY * NVL(COMMISSION_PCT, 0)) AS COMM_SAL
						  FROM EMPLOYEES
						 ORDER BY COMM_SAL DESC))
;						 

SELECT FIRST_NAME
  	 , COMM_SAL
	 , ROW_NUMBER() OVER(ORDER BY COMM_SAL DESC) AS SAL_NUM
 FROM(SELECT FIRST_NAME
		   , SALARY + (SALARY * NVL(COMMISSION_PCT, 0)) AS COMM_SAL
		FROM EMPLOYEES)
;

SELECT FIRST_NAME
	 , COMM_SAL
  FROM (SELECT FIRST_NAME
			 , COMM_SAL
			 , RNUM
		  FROM (SELECT FIRST_NAME
					 , COMM_SAL
					 , ROWNUM AS RNUM
				  FROM (SELECT FIRST_NAME
							 , SALARY
							 , SALARY+ (SALARY * NVL(COMMISSION_PCT, 0)) AS COMM_SAL
						  FROM EMPLOYEES
						 ORDER BY COMM_SAL DESC
						 	 , FIRST_NAME ASC))
		 WHERE RNUM <= 16)	
 WHERE RNUM >= 7		 
;

SELECT FIRST_NAME
	 , COMM_SAL
  FROM (SELECT FIRST_NAME
  			 , COMM_SAL
			 , ROW_NUMBER() OVER(ORDER BY COMM_SAL DESC, FIRST_NAME ASC) AS SAL_NUM
		  FROM (SELECT FIRST_NAME
					 , SALARY + (SALARY * NVL(COMMISSION_PCT, 0)) AS COMM_SAL
				  FROM EMPLOYEES))	
 WHERE SAL_NUM >= 7
   AND SAL_NUM <= 16
;

SELECT *
  FROM EMPLOYEES
;
-- RANK() OVER() -- ANSI
-- 공동1등 3명, 2등2명, 3등3명, 1등 1명--> 1 1 1 4 4 6 6 6 9
SELECT SALARY
	 , RANK() OVER( ORDER BY SALARY DESC) AS RANK
  FROM EMPLOYEES
;
-- DENSE_RANK() OVER() -- ANSI
-- 공동1등 3명, 2등2명, 3등 3명, 4등 1명 --> 1 1 1 2 2 3 3 3 4
SELECT SALARY
	 , DENSE_RANK() OVER( ORDER BY SALARY DESC) AS RANK
  FROM EMPLOYEES
;
-- ROW_NUMBER() OVER() -- ANSI
-- 공동1등 3명, 2등 2명, 3등 3명, 4등 1명 --> 1 2 3 4 5 6 7 8 9
SELECT SALARY
	 , ROW_NUMBER() OVER( ORDER BY SALARY DESC) AS RANK
  FROM EMPLOYEES
;
-- ROWNUM - ANSI X
-- 공동1등 3명, 2등2명, 3등 3명, 4등 1명 --> 1 2 3 4 5 6 7 8 9
SELECT SALARY
  FROM EMPLOYEES
;
-- INLINE VIEW 
SELECT *
  FROM EMP_DETAILS_VIEW EDV 
;

-- 70, 80, 90, 100 번 부서에서 근무중인 사원의 이름과 부서명을 조회한다.
SELECT E.FIRST_NAME
	 , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE D.DEPARTMENT_ID IN (70, 80, 90, 100)
 ORDER BY D.DEPARTMENT_ID
;
-- INLINE VIEW 를 이용한 성능 향상
SELECT E.FIRST_NAME
	 , D.DEPARTMENT_NAME
  FROM (SELECT FIRST_NAME
  			 , DEPARTMENT_ID
  		  FROM EMPLOYEES
  		 WHERE DEPARTMENT_ID IN (70, 80, 90, 100) )E
 INNER JOIN (SELECT DEPARTMENT_ID
 				  , DEPARTMENT_NAME
 			   FROM DEPARTMENTS
 			  WHERE DEPARTMENT_ID IN (70, 80, 90, 100)) D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 ORDER BY D.DEPARTMENT_ID
;

-- 입사 연도별 최고 급여를 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	 , MAX(SALARY)
  FROM EMPLOYEES
 GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
;

-- INLINE VIEW
SELECT SALARY
	 , TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR
  FROM EMPLOYEES
;
SELECT HIRE_YEAR
	 , MAX(SALARY)
  FROM(SELECT SALARY
	 		, TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR
  		 FROM EMPLOYEES)
 GROUP BY HIRE_YEAR
;
-- 입사 연도별 사원의 수를 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY')
	 , COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
;

-- INLINE VIEW
SELECT HIRE_YEAR
	 , COUNT(EMPLOYEE_ID)
  FROM(SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR
	 		, EMPLOYEE_ID
  		 FROM EMPLOYEES)
 GROUP BY HIRE_YEAR
;

-- 사원의 이름의 첫 번째 글자만 가져온다(ANSI X)
SELECT FIRST_NAME
	 , SUBSTR(FIRST_NAME, 1, 1)
  FROM EMPLOYEES
;
-- 사원 이름의 첫 번째 글자별 급여 합계를 가져온다.
SELECT SUBSTR(FIRST_NAME, 1, 1) AS NAME
	 , SUM(SALARY)
  FROM EMPLOYEES
 GROUP BY SUBSTR(FIRST_NAME, 1, 1)
 ORDER BY NAME ASC
;
-- INLINE VIEW
SELECT E.NAME 
	 , SUM(E.SALARY)
  FROM (SELECT SUBSTR(FIRST_NAME, 1, 1) AS NAME
  			 , SALARY
  		  FROM EMPLOYEES)E
 GROUP BY E.NAME 
 ORDER BY E.NAME ASC
;
-- 테이블 조인 + 그룹핑
-- 직무명 별 수행중인 사원의 수를 조회한다.
SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
;
-- 직무명 별 수행중인 사원의 수를 조회한다. 직무명으로 오름차순 정렬
SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
 ORDER BY J.JOB_TITLE ASC
;
-- 직무명 별 수행중인 사원의 수를 조회한다. 사원의 수로 내림차순 정렬
SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 GROUP BY J.JOB_TITLE 
 ORDER BY EMP_CNT DESC
;

-- 테이블 조인 + 조건
-- 108번 사원의 이름과 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.EMPLOYEE_ID = 108
;

-- 108번 사원의 이름과 부서명을 조회한다.(조인 최적화)
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.EMPLOYEE_ID = 108
   AND E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;

-- 직무의 아이디가 AD_VP이거나 부서의 번호가 70번인 사원의 이름, 직무 명, 부서 명 조회한다.
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 WHERE J.JOB_ID = 'AD_VP'
 	OR D.DEPARTMENT_ID = 70
;

-- 직무명이 Administration Vice President 이거나 부서의 번호가 70번인 사원의 이름, 부서 명 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID  
 WHERE E.DEPARTMENT_ID = 70
 	OR E.JOB_ID = (SELECT J.JOB_ID
 					 FROM JOBS J
 					WHERE J.JOB_TITLE = 'Administration Vice President')
;

-- Europe에 근무중인 모든 사원의 이름과 근무중인 도시를 조회한다.
SELECT E.FIRST_NAME
	 , L.CITY
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID
 WHERE L.COUNTRY_ID IN (SELECT C.COUNTRY_ID
 						  FROM COUNTRIES C 
 						 WHERE C.REGION_ID = (SELECT R.REGION_ID
 						 						FROM REGIONS R
 						 					   WHERE R.REGION_NAME = 'Europe'))
;
-- 직무가 변경된 사원들의 사원번호, 이름, 급여, 현재 수행중인 직무의 이름, 과거에 근무했던 부서의 이름, 현재 근무중인 부서의 이름을 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.SALARY 
	 , J.JOB_TITLE AS PRESENT_JOB
	 , DEPT_PAST.DEPARTMENT_NAME AS PAST_DEPT
	 , DEPT_PRES.DEPARTMENT_NAME AS PRES_DEPT
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH  -- 직무변경이력 + 사원
 	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
 INNER JOIN JOBS J -- 사원 + 직무
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN DEPARTMENTS DEPT_PRES --사원 + 부서
 	ON E.DEPARTMENT_ID = DEPT_PRES.DEPARTMENT_ID 
 INNER JOIN DEPARTMENTS DEPT_PAST -- 직무변경이력 + 부서
 	ON DEPT_PAST.DEPARTMENT_ID = JH.DEPARTMENT_ID 
 ;

-- 테이블 조인(여러 테이블을 관계를 이용해 하나의 테이블로 만드는 과정) 연습
-- 사원 테이블 + 부서 테이블 == > 사원_부서
-- 사원의 이름, 사원의 성, 급여, 부서장의 사원번호,부서명
SELECT EMPLOYEES.FIRST_NAME
	 , EMPLOYEES.LAST_NAME 
	 , EMPLOYEES.SALARY
	 , DEPARTMENTS.MANAGER_ID
	 , DEPARTMENTS.DEPARTMENT_NAME
  FROM EMPLOYEES
 INNER JOIN DEPARTMENTS
 	ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID 
;

-- 사원의 이름과 성, 직무아이디, 직무의 이름, 급여, 최대 급여, 최소 급여를 조회한다.
SELECT e.FIRST_NAME 
	 , e.LAST_NAME 
	 , j.JOB_ID 
	 , j.JOB_TITLE 
	 , e.SALARY 
	 , j.MAX_SALARY 
	 , j.MIN_SALARY 
  FROM EMPLOYEES e
 INNER JOIN JOBS j 
 	ON e.JOB_ID = j.JOB_ID
;

-- 3개 이상 테이블 조인 방법
-- 사원 + 부서 + 직무
SELECT *
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D -- 사원 + 부서
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J -- 사원 + 직무
	ON E.JOB_ID = J.JOB_ID 
; 	
-- 사원 + 부서 + 직무 + 지역
SELECT *
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID 
;
-- 자원 + 부서 + 지역 + 국가 + 대륙
SELECT *
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L 
 	ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R 
 	ON C.REGION_ID = R.REGION_ID 
;

-- 80번 부서의 부서장으로 근무하는 사원의 직무명을 조회한다.
SELECT MANAGER_ID 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = 80
;
SELECT JOB_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID 
  						FROM DEPARTMENTS
 					   WHERE DEPARTMENT_ID = 80)			
;
SELECT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID = (SELECT JOB_ID
  				   FROM EMPLOYEES
 				  WHERE EMPLOYEE_ID = (SELECT MANAGER_ID 
  										 FROM DEPARTMENTS
 					   					WHERE DEPARTMENT_ID = 80))
; 					   					
-- 103번 사원이 근무중인 부서의 이름을 조회한다.
SELECT d.DEPARTMENT_NAME 
  FROM DEPARTMENTS d 
 WHERE d.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
 							 FROM EMPLOYEES e 
 							WHERE e.EMPLOYEE_ID  = 103)
;
-- 118번 사원이 근무중인 부서의 도시명을 조회한다.
SELECT l.CITY  
  FROM DEPARTMENTS d , LOCATIONS l 
 WHERE d.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
 							 FROM EMPLOYEES e 
 							WHERE e.EMPLOYEE_ID  = 118)
   AND l.LOCATION_ID = d.LOCATION_ID  
;
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID = (SELECT LOCATION_ID 
 						FROM DEPARTMENTS
 					   WHERE DEPARTMENT_ID  = (SELECT DEPARTMENT_ID 
 					   							 FROM EMPLOYEES
 					   							WHERE EMPLOYEE_ID = 118))
;
-- 102번 사원이 수행중인 직무의 이름과 최대 급여, 최소 급여를 조회한다.
SELECT JOB_TITLE 
	 , MAX_SALARY 
	 , MIN_SALARY 
  FROM JOBS
 WHERE JOB_ID IN (SELECT EMPLOYEES.JOB_ID 
 					FROM EMPLOYEES
 				   WHERE EMPLOYEE_ID = 102)
;

-- Seattle에서 근무중인 사원들의 직무 명을 중복없이 조회한다.
SELECT JOB_TITLE
  FROM JOBS
 WHERE JOB_ID IN (SELECT DISTINCT JOB_ID
 					FROM EMPLOYEES
 				   WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
 				   							 FROM DEPARTMENTS
 											WHERE LOCATION_ID IN (SELECT LOCATION_ID
 						   											FROM LOCATIONS
 						 										   WHERE CITY = 'Seattle' 
 							 										)
 							 				)		 
 				   )
 
;
-- Seattle에 있는 부서의 이름과 부서장의 사원 번호를 조회한다
SELECT d.DEPARTMENT_NAME 
	 , d.MANAGER_ID 
  FROM DEPARTMENTS d 
 WHERE d.LOCATION_ID IN (SELECT l.LOCATION_ID
 						   FROM LOCATIONS l
 						  WHERE l.CITY = 'Seattle' 
 							 )
;
 
-- Asia에 근무중인 사원들의 이름과 성, 부서 번호를 조회한다.
SELECT e.FIRST_NAME 
	 , e.LAST_NAME 
	 , e.DEPARTMENT_ID 
  FROM EMPLOYEES e 
 WHERE e.DEPARTMENT_ID IN (SELECT d.DEPARTMENT_ID 
 							 FROM DEPARTMENTS d 
 							WHERE d.LOCATION_ID IN (SELECT l.LOCATION_ID 
 													  FROM LOCATIONS l 
 													 WHERE l.COUNTRY_ID IN (SELECT c.COUNTRY_ID 
 													 						  FROM COUNTRIES c 
 													 						 WHERE c.REGION_ID IN (SELECT r.REGION_ID 
 													 						 						 FROM REGIONS r 
 													 						 						WHERE r.REGION_NAME = 'Asia'
 													 												)
 													 						) 
 													 )
 							)
;



-- 101. 직무가 변경된 사원의 과거 직무명과 현재 직무명을 조회한다.
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE AS PRESENT
	 , J_PAST.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J 
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN JOB_HISTORY JH 
 	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 INNER JOIN JOBS J_PAST
	ON J_PAST.JOB_ID = JH.JOB_ID 
 ;