CREATE TABLE "MV" (
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"TTL"	VARCHAR2 (40 CHAR)		NOT NULL,
	"MV_RTNG"	VARCHAR2 (3 CHAR)		NULL,
	"RNNG_TM"	NUMBER (5,0)		NULL,
	"RLS_DT"	DATE		NULL,
	"SMMR"	VARCHAR2 (420 CHAR)		NULL,
	"MAIN_PSTR_URL"	CLOB		NOT NULL,
	"FB_URL"	VARCHAR2 (4000 CHAR)		NULL,
	"X_URL"	VARCHAR2 (4000 CHAR)		NULL,
	"INSTGRM_URL"	VARCHAR2 (4000 CHAR)		NULL,
	"TGLN"	VARCHAR2 (55 CHAR)		NULL,
	"ORGNL_TTL"	VARCHAR2 (45 CHAR)		NULL,
	"PLYNG"	VARCHAR2 (5 CHAR)		NOT NULL,
	"LNGG"	VARCHAR2 (5 CHAR)		NOT NULL,
	"BDGT"	NUMBER (10, 0)		NULL,
	"BX_OFFC_GRSS"	NUMBER (10, 0)		NULL
);

CREATE TABLE "GNR" (
	"GNR_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"NM"	VARCHAR2 (20 CHAR)		NOT NULL
);

CREATE TABLE "MV_GNR" (
	"MV_GNR_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"GNR_ID2"	VARCHAR2 (20 CHAR)		NOT NULL
);

COMMENT ON COLUMN "MV_GNR"."MV_GNR_ID" IS 'MG-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "INVLVD" (
	"INVLVD_ID"	VARCHAR2 (40 CHAR)		NOT NULL,
	"INVLVD_PRFL"	CLOB		NULL,
	"INVLVD_NAME"	VARCHAR2 (20 CHAR)		NOT NULL
);

CREATE TABLE "FLMMKR" (
	"FLMMKR_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"INVLVD_ID"	VARCHAR2 (40 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"FLMMKR_RL"	VARCHAR2 (30 CHAR)		NOT NULL,
	"FLMMKR_PRT"	VARCHAR2 (10 CHAR)		NOT NULL
);

COMMENT ON COLUMN "FLMMKR"."FLMMKR_ID" IS 'FM-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "STR" (
	"APPR_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"INVLVD_ID"	VARCHAR2 (40 CHAR)		NOT NULL,
	"STR_NM"	VARCHAR2 (30 CHAR)		NOT NULL
);

COMMENT ON COLUMN "STR"."APPR_ID" IS 'AP-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "KWED" (
	"KWRD_ID"	VARCHAR2 (30CHAR)		NOT NULL,
	"KWRD_NM"	VARCHAR2 (30 CHAR)		NOT NULL
);

CREATE TABLE "MV_KWRD" (
	"MV_KWRD_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"KWRD_ID2"	VARCHAR2 (20 CHAR)		NOT NULL
);

COMMENT ON COLUMN "MV_KWRD"."MV_KWRD_ID" IS 'MK-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "VD" (
	"VD_ID"	VARCHAR2 (20CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"VD_URL"	CLOB		NOT NULL
);

COMMENT ON COLUMN "VD"."VD_ID" IS 'VD-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "BCKGRND" (
	"BCKGRND_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"BCKGRND_URL"	CLOB		NOT NULL
);

COMMENT ON COLUMN "BCKGRND"."BCKGRND_ID" IS 'BG-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "PSTR" (
	"PSTR_ID"	VARCHAR2 (20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2 (50 CHAR)		NOT NULL,
	"PSTR_URL"	CLOB		NOT NULL
);

COMMENT ON COLUMN "PSTR"."PSTR_ID" IS 'PS-연월일(8자리)-일련번호(6자리)';

ALTER TABLE "MV" ADD CONSTRAINT "PK_MV" PRIMARY KEY (
	"MV_ID"
);

ALTER TABLE "GNR" ADD CONSTRAINT "PK_GNR" PRIMARY KEY (
	"GNR_ID"
);

ALTER TABLE "MV_GNR" ADD CONSTRAINT "PK_MV_GNR" PRIMARY KEY (
	"MV_GNR_ID"
);

ALTER TABLE "INVLVD" ADD CONSTRAINT "PK_INVLVD" PRIMARY KEY (
	"INVLVD_ID"
);

ALTER TABLE "FLMMKR" ADD CONSTRAINT "PK_FLMMKR" PRIMARY KEY (
	"FLMMKR_ID"
);

ALTER TABLE "STR" ADD CONSTRAINT "PK_STR" PRIMARY KEY (
	"APPR_ID"
);

ALTER TABLE "KWED" ADD CONSTRAINT "PK_KWED" PRIMARY KEY (
	"KWRD_ID"
);

ALTER TABLE "MV_KWRD" ADD CONSTRAINT "PK_MV_KWRD" PRIMARY KEY (
	"MV_KWRD_ID"
);

ALTER TABLE "VD" ADD CONSTRAINT "PK_VD" PRIMARY KEY (
	"VD_ID"
);

ALTER TABLE "BCKGRND" ADD CONSTRAINT "PK_BCKGRND" PRIMARY KEY (
	"BCKGRND_ID"
);

ALTER TABLE "PSTR" ADD CONSTRAINT "PK_PSTR" PRIMARY KEY (
	"PSTR_ID"
);

ALTER TABLE "MV_GNR" ADD CONSTRAINT "FK_MV_TO_MV_GNR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "MV_GNR" ADD CONSTRAINT "FK_GNR_TO_MV_GNR_1" FOREIGN KEY (
	"GNR_ID2"
)
REFERENCES "GNR" (
	"GNR_ID"
);

ALTER TABLE "FLMMKR" ADD CONSTRAINT "FK_INVLVD_TO_FLMMKR_1" FOREIGN KEY (
	"INVLVD_ID"
)
REFERENCES "INVLVD" (
	"INVLVD_ID"
);

ALTER TABLE "FLMMKR" ADD CONSTRAINT "FK_MV_TO_FLMMKR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "STR" ADD CONSTRAINT "FK_MV_TO_STR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "STR" ADD CONSTRAINT "FK_INVLVD_TO_STR_1" FOREIGN KEY (
	"INVLVD_ID"
)
REFERENCES "INVLVD" (
	"INVLVD_ID"
);

ALTER TABLE "MV_KWRD" ADD CONSTRAINT "FK_MV_TO_MV_KWRD_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "MV_KWRD" ADD CONSTRAINT "FK_KWED_TO_MV_KWRD_1" FOREIGN KEY (
	"KWRD_ID2"
)
REFERENCES "KWED" (
	"KWRD_ID"
);

ALTER TABLE "VD" ADD CONSTRAINT "FK_MV_TO_VD_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "BCKGRND" ADD CONSTRAINT "FK_MV_TO_BCKGRND_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "PSTR" ADD CONSTRAINT "FK_MV_TO_PSTR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

