--1. 대륙, 국가, 도시, 부서, 직무별 사원의 수, 사원들의 평균 급여를 조회하세요.
SELECT R.REGION_NAME
	 , C.COUNTRY_NAME 
	 , L.CITY 
	 , D.DEPARTMENT_NAME
	 , J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID )
	 , AVG(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D 
 	ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C 
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R 
 	ON C.REGION_ID = R.REGION_ID 
 GROUP BY R.REGION_NAME 
 	 , C.COUNTRY_NAME 
 	 , L.CITY 
 	 , D.DEPARTMENT_NAME
 	 , J.JOB_TITLE
;
 
--2. 각 부서장 사원번호별 사원의 수를 조회하고 사원의 수로 오름차순 정렬하세요.
SELECT E.MANAGER_ID  
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D 
 	ON E.MANAGER_ID = D.MANAGER_ID
 GROUP BY E.MANAGER_ID
;
--3. 직무가 받을 수 있는 평균 급여(MAX_SALARY, MIN_SALARY)보다 많은 급여를 받는 사원들을 직무별 사원의 수로 조회하세요.
SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E 
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 WHERE E.SALARY > (J.MAX_SALARY +J.MIN_SALARY )/2
 GROUP BY J.JOB_TITLE 
;
--4. 모든 부서장들의 부하직원들을 계층 조회하세요.
